// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"main/internal/modules/class/domain"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClassRepositoryI creates a new instance of MockClassRepositoryI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClassRepositoryI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClassRepositoryI {
	mock := &MockClassRepositoryI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClassRepositoryI is an autogenerated mock type for the ClassRepositoryI type
type MockClassRepositoryI struct {
	mock.Mock
}

type MockClassRepositoryI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClassRepositoryI) EXPECT() *MockClassRepositoryI_Expecter {
	return &MockClassRepositoryI_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockClassRepositoryI
func (_mock *MockClassRepositoryI) Create(ctx context.Context, data *domain.Class) (*domain.Class, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Class
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Class) (*domain.Class, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Class) *domain.Class); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Class)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.Class) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClassRepositoryI_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockClassRepositoryI_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - data *domain.Class
func (_e *MockClassRepositoryI_Expecter) Create(ctx any, data any) *MockClassRepositoryI_Create_Call {
	return &MockClassRepositoryI_Create_Call{Call: _e.mock.On("Create", ctx, data)}
}

func (_c *MockClassRepositoryI_Create_Call) Run(run func(ctx context.Context, data *domain.Class)) *MockClassRepositoryI_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Class
		if args[1] != nil {
			arg1 = args[1].(*domain.Class)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClassRepositoryI_Create_Call) Return(class *domain.Class, err error) *MockClassRepositoryI_Create_Call {
	_c.Call.Return(class, err)
	return _c
}

func (_c *MockClassRepositoryI_Create_Call) RunAndReturn(run func(ctx context.Context, data *domain.Class) (*domain.Class, error)) *MockClassRepositoryI_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockClassRepositoryI
func (_mock *MockClassRepositoryI) Delete(ctx context.Context, classID uuid.UUID) error {
	ret := _mock.Called(ctx, classID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, classID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClassRepositoryI_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockClassRepositoryI_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - classID uuid.UUID
func (_e *MockClassRepositoryI_Expecter) Delete(ctx any, classID any) *MockClassRepositoryI_Delete_Call {
	return &MockClassRepositoryI_Delete_Call{Call: _e.mock.On("Delete", ctx, classID)}
}

func (_c *MockClassRepositoryI_Delete_Call) Run(run func(ctx context.Context, classID uuid.UUID)) *MockClassRepositoryI_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClassRepositoryI_Delete_Call) Return(err error) *MockClassRepositoryI_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClassRepositoryI_Delete_Call) RunAndReturn(run func(ctx context.Context, classID uuid.UUID) error) *MockClassRepositoryI_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockClassRepositoryI
func (_mock *MockClassRepositoryI) GetAll(ctx context.Context) (*[]domain.Class, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 *[]domain.Class
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*[]domain.Class, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *[]domain.Class); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]domain.Class)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClassRepositoryI_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockClassRepositoryI_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClassRepositoryI_Expecter) GetAll(ctx any) *MockClassRepositoryI_GetAll_Call {
	return &MockClassRepositoryI_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockClassRepositoryI_GetAll_Call) Run(run func(ctx context.Context)) *MockClassRepositoryI_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClassRepositoryI_GetAll_Call) Return(classs *[]domain.Class, err error) *MockClassRepositoryI_GetAll_Call {
	_c.Call.Return(classs, err)
	return _c
}

func (_c *MockClassRepositoryI_GetAll_Call) RunAndReturn(run func(ctx context.Context) (*[]domain.Class, error)) *MockClassRepositoryI_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockClassRepositoryI
func (_mock *MockClassRepositoryI) GetByID(ctx context.Context, classID uuid.UUID) (*domain.Class, error) {
	ret := _mock.Called(ctx, classID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Class
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Class, error)); ok {
		return returnFunc(ctx, classID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Class); ok {
		r0 = returnFunc(ctx, classID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Class)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, classID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClassRepositoryI_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockClassRepositoryI_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - classID uuid.UUID
func (_e *MockClassRepositoryI_Expecter) GetByID(ctx any, classID any) *MockClassRepositoryI_GetByID_Call {
	return &MockClassRepositoryI_GetByID_Call{Call: _e.mock.On("GetByID", ctx, classID)}
}

func (_c *MockClassRepositoryI_GetByID_Call) Run(run func(ctx context.Context, classID uuid.UUID)) *MockClassRepositoryI_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClassRepositoryI_GetByID_Call) Return(class *domain.Class, err error) *MockClassRepositoryI_GetByID_Call {
	_c.Call.Return(class, err)
	return _c
}

func (_c *MockClassRepositoryI_GetByID_Call) RunAndReturn(run func(ctx context.Context, classID uuid.UUID) (*domain.Class, error)) *MockClassRepositoryI_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBySystemID provides a mock function for the type MockClassRepositoryI
func (_mock *MockClassRepositoryI) GetBySystemID(ctx context.Context, systemID string) (*domain.Class, error) {
	ret := _mock.Called(ctx, systemID)

	if len(ret) == 0 {
		panic("no return value specified for GetBySystemID")
	}

	var r0 *domain.Class
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Class, error)); ok {
		return returnFunc(ctx, systemID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Class); ok {
		r0 = returnFunc(ctx, systemID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Class)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, systemID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClassRepositoryI_GetBySystemID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBySystemID'
type MockClassRepositoryI_GetBySystemID_Call struct {
	*mock.Call
}

// GetBySystemID is a helper method to define mock.On call
//   - ctx context.Context
//   - systemID string
func (_e *MockClassRepositoryI_Expecter) GetBySystemID(ctx any, systemID any) *MockClassRepositoryI_GetBySystemID_Call {
	return &MockClassRepositoryI_GetBySystemID_Call{Call: _e.mock.On("GetBySystemID", ctx, systemID)}
}

func (_c *MockClassRepositoryI_GetBySystemID_Call) Run(run func(ctx context.Context, systemID string)) *MockClassRepositoryI_GetBySystemID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClassRepositoryI_GetBySystemID_Call) Return(class *domain.Class, err error) *MockClassRepositoryI_GetBySystemID_Call {
	_c.Call.Return(class, err)
	return _c
}

func (_c *MockClassRepositoryI_GetBySystemID_Call) RunAndReturn(run func(ctx context.Context, systemID string) (*domain.Class, error)) *MockClassRepositoryI_GetBySystemID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockClassRepositoryI
func (_mock *MockClassRepositoryI) Update(ctx context.Context, data *domain.Class) (*domain.Class, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Class
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Class) (*domain.Class, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Class) *domain.Class); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Class)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.Class) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClassRepositoryI_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockClassRepositoryI_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - data *domain.Class
func (_e *MockClassRepositoryI_Expecter) Update(ctx any, data any) *MockClassRepositoryI_Update_Call {
	return &MockClassRepositoryI_Update_Call{Call: _e.mock.On("Update", ctx, data)}
}

func (_c *MockClassRepositoryI_Update_Call) Run(run func(ctx context.Context, data *domain.Class)) *MockClassRepositoryI_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Class
		if args[1] != nil {
			arg1 = args[1].(*domain.Class)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClassRepositoryI_Update_Call) Return(class *domain.Class, err error) *MockClassRepositoryI_Update_Call {
	_c.Call.Return(class, err)
	return _c
}

func (_c *MockClassRepositoryI_Update_Call) RunAndReturn(run func(ctx context.Context, data *domain.Class) (*domain.Class, error)) *MockClassRepositoryI_Update_Call {
	_c.Call.Return(run)
	return _c
}

