// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"main/internal/modules/class"
	"main/internal/modules/class/domain"

	"github.com/gin-gonic/gin"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIRepository creates a new instance of MockIRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRepository {
	mock := &MockIRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIRepository is an autogenerated mock type for the IRepository type
type MockIRepository struct {
	mock.Mock
}

type MockIRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRepository) EXPECT() *MockIRepository_Expecter {
	return &MockIRepository_Expecter{mock: &_m.Mock}
}

// CreateClass provides a mock function for the type MockIRepository
func (_mock *MockIRepository) CreateClass(ctx context.Context, data *domain.Class) (*domain.Class, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateClass")
	}

	var r0 *domain.Class
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Class) (*domain.Class, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Class) *domain.Class); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Class)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.Class) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRepository_CreateClass_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateClass'
type MockIRepository_CreateClass_Call struct {
	*mock.Call
}

// CreateClass is a helper method to define mock.On call
//   - ctx context.Context
//   - data *domain.Class
func (_e *MockIRepository_Expecter) CreateClass(ctx any, data any) *MockIRepository_CreateClass_Call {
	return &MockIRepository_CreateClass_Call{Call: _e.mock.On("CreateClass", ctx, data)}
}

func (_c *MockIRepository_CreateClass_Call) Run(run func(ctx context.Context, data *domain.Class)) *MockIRepository_CreateClass_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Class
		if args[1] != nil {
			arg1 = args[1].(*domain.Class)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIRepository_CreateClass_Call) Return(class *domain.Class, err error) *MockIRepository_CreateClass_Call {
	_c.Call.Return(class, err)
	return _c
}

func (_c *MockIRepository_CreateClass_Call) RunAndReturn(run func(ctx context.Context, data *domain.Class) (*domain.Class, error)) *MockIRepository_CreateClass_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteClass provides a mock function for the type MockIRepository
func (_mock *MockIRepository) DeleteClass(ctx context.Context, classID uuid.UUID) error {
	ret := _mock.Called(ctx, classID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteClass")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, classID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIRepository_DeleteClass_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteClass'
type MockIRepository_DeleteClass_Call struct {
	*mock.Call
}

// DeleteClass is a helper method to define mock.On call
//   - ctx context.Context
//   - classID uuid.UUID
func (_e *MockIRepository_Expecter) DeleteClass(ctx any, classID any) *MockIRepository_DeleteClass_Call {
	return &MockIRepository_DeleteClass_Call{Call: _e.mock.On("DeleteClass", ctx, classID)}
}

func (_c *MockIRepository_DeleteClass_Call) Run(run func(ctx context.Context, classID uuid.UUID)) *MockIRepository_DeleteClass_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIRepository_DeleteClass_Call) Return(err error) *MockIRepository_DeleteClass_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIRepository_DeleteClass_Call) RunAndReturn(run func(ctx context.Context, classID uuid.UUID) error) *MockIRepository_DeleteClass_Call {
	_c.Call.Return(run)
	return _c
}

// GetClassByID provides a mock function for the type MockIRepository
func (_mock *MockIRepository) GetClassByID(ctx context.Context, classID uuid.UUID) (*domain.Class, error) {
	ret := _mock.Called(ctx, classID)

	if len(ret) == 0 {
		panic("no return value specified for GetClassByID")
	}

	var r0 *domain.Class
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Class, error)); ok {
		return returnFunc(ctx, classID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Class); ok {
		r0 = returnFunc(ctx, classID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Class)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, classID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRepository_GetClassByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClassByID'
type MockIRepository_GetClassByID_Call struct {
	*mock.Call
}

// GetClassByID is a helper method to define mock.On call
//   - ctx context.Context
//   - classID uuid.UUID
func (_e *MockIRepository_Expecter) GetClassByID(ctx any, classID any) *MockIRepository_GetClassByID_Call {
	return &MockIRepository_GetClassByID_Call{Call: _e.mock.On("GetClassByID", ctx, classID)}
}

func (_c *MockIRepository_GetClassByID_Call) Run(run func(ctx context.Context, classID uuid.UUID)) *MockIRepository_GetClassByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIRepository_GetClassByID_Call) Return(class *domain.Class, err error) *MockIRepository_GetClassByID_Call {
	_c.Call.Return(class, err)
	return _c
}

func (_c *MockIRepository_GetClassByID_Call) RunAndReturn(run func(ctx context.Context, classID uuid.UUID) (*domain.Class, error)) *MockIRepository_GetClassByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetClassBySystemID provides a mock function for the type MockIRepository
func (_mock *MockIRepository) GetClassBySystemID(ctx context.Context, systemID string) (*domain.Class, error) {
	ret := _mock.Called(ctx, systemID)

	if len(ret) == 0 {
		panic("no return value specified for GetClassBySystemID")
	}

	var r0 *domain.Class
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Class, error)); ok {
		return returnFunc(ctx, systemID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Class); ok {
		r0 = returnFunc(ctx, systemID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Class)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, systemID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRepository_GetClassBySystemID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClassBySystemID'
type MockIRepository_GetClassBySystemID_Call struct {
	*mock.Call
}

// GetClassBySystemID is a helper method to define mock.On call
//   - ctx context.Context
//   - systemID string
func (_e *MockIRepository_Expecter) GetClassBySystemID(ctx any, systemID any) *MockIRepository_GetClassBySystemID_Call {
	return &MockIRepository_GetClassBySystemID_Call{Call: _e.mock.On("GetClassBySystemID", ctx, systemID)}
}

func (_c *MockIRepository_GetClassBySystemID_Call) Run(run func(ctx context.Context, systemID string)) *MockIRepository_GetClassBySystemID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIRepository_GetClassBySystemID_Call) Return(class *domain.Class, err error) *MockIRepository_GetClassBySystemID_Call {
	_c.Call.Return(class, err)
	return _c
}

func (_c *MockIRepository_GetClassBySystemID_Call) RunAndReturn(run func(ctx context.Context, systemID string) (*domain.Class, error)) *MockIRepository_GetClassBySystemID_Call {
	_c.Call.Return(run)
	return _c
}

// GetClasses provides a mock function for the type MockIRepository
func (_mock *MockIRepository) GetClasses(ctx context.Context) (*[]domain.Class, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetClasses")
	}

	var r0 *[]domain.Class
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*[]domain.Class, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *[]domain.Class); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]domain.Class)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRepository_GetClasses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClasses'
type MockIRepository_GetClasses_Call struct {
	*mock.Call
}

// GetClasses is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIRepository_Expecter) GetClasses(ctx any) *MockIRepository_GetClasses_Call {
	return &MockIRepository_GetClasses_Call{Call: _e.mock.On("GetClasses", ctx)}
}

func (_c *MockIRepository_GetClasses_Call) Run(run func(ctx context.Context)) *MockIRepository_GetClasses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIRepository_GetClasses_Call) Return(classs *[]domain.Class, err error) *MockIRepository_GetClasses_Call {
	_c.Call.Return(classs, err)
	return _c
}

func (_c *MockIRepository_GetClasses_Call) RunAndReturn(run func(ctx context.Context) (*[]domain.Class, error)) *MockIRepository_GetClasses_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateClass provides a mock function for the type MockIRepository
func (_mock *MockIRepository) UpdateClass(ctx context.Context, data *domain.Class) (*domain.Class, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateClass")
	}

	var r0 *domain.Class
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Class) (*domain.Class, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Class) *domain.Class); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Class)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.Class) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRepository_UpdateClass_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateClass'
type MockIRepository_UpdateClass_Call struct {
	*mock.Call
}

// UpdateClass is a helper method to define mock.On call
//   - ctx context.Context
//   - data *domain.Class
func (_e *MockIRepository_Expecter) UpdateClass(ctx any, data any) *MockIRepository_UpdateClass_Call {
	return &MockIRepository_UpdateClass_Call{Call: _e.mock.On("UpdateClass", ctx, data)}
}

func (_c *MockIRepository_UpdateClass_Call) Run(run func(ctx context.Context, data *domain.Class)) *MockIRepository_UpdateClass_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Class
		if args[1] != nil {
			arg1 = args[1].(*domain.Class)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIRepository_UpdateClass_Call) Return(class *domain.Class, err error) *MockIRepository_UpdateClass_Call {
	_c.Call.Return(class, err)
	return _c
}

func (_c *MockIRepository_UpdateClass_Call) RunAndReturn(run func(ctx context.Context, data *domain.Class) (*domain.Class, error)) *MockIRepository_UpdateClass_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIController creates a new instance of MockIController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIController(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIController {
	mock := &MockIController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIController is an autogenerated mock type for the IController type
type MockIController struct {
	mock.Mock
}

type MockIController_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIController) EXPECT() *MockIController_Expecter {
	return &MockIController_Expecter{mock: &_m.Mock}
}

// CreateClass provides a mock function for the type MockIController
func (_mock *MockIController) CreateClass(c *gin.Context) {
	_mock.Called(c)
	return
}

// MockIController_CreateClass_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateClass'
type MockIController_CreateClass_Call struct {
	*mock.Call
}

// CreateClass is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockIController_Expecter) CreateClass(c any) *MockIController_CreateClass_Call {
	return &MockIController_CreateClass_Call{Call: _e.mock.On("CreateClass", c)}
}

func (_c *MockIController_CreateClass_Call) Run(run func(c *gin.Context)) *MockIController_CreateClass_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIController_CreateClass_Call) Return() *MockIController_CreateClass_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIController_CreateClass_Call) RunAndReturn(run func(c *gin.Context)) *MockIController_CreateClass_Call {
	_c.Run(run)
	return _c
}

// DeleteClass provides a mock function for the type MockIController
func (_mock *MockIController) DeleteClass(c *gin.Context) {
	_mock.Called(c)
	return
}

// MockIController_DeleteClass_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteClass'
type MockIController_DeleteClass_Call struct {
	*mock.Call
}

// DeleteClass is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockIController_Expecter) DeleteClass(c any) *MockIController_DeleteClass_Call {
	return &MockIController_DeleteClass_Call{Call: _e.mock.On("DeleteClass", c)}
}

func (_c *MockIController_DeleteClass_Call) Run(run func(c *gin.Context)) *MockIController_DeleteClass_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIController_DeleteClass_Call) Return() *MockIController_DeleteClass_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIController_DeleteClass_Call) RunAndReturn(run func(c *gin.Context)) *MockIController_DeleteClass_Call {
	_c.Run(run)
	return _c
}

// GetClassByID provides a mock function for the type MockIController
func (_mock *MockIController) GetClassByID(c *gin.Context) {
	_mock.Called(c)
	return
}

// MockIController_GetClassByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClassByID'
type MockIController_GetClassByID_Call struct {
	*mock.Call
}

// GetClassByID is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockIController_Expecter) GetClassByID(c any) *MockIController_GetClassByID_Call {
	return &MockIController_GetClassByID_Call{Call: _e.mock.On("GetClassByID", c)}
}

func (_c *MockIController_GetClassByID_Call) Run(run func(c *gin.Context)) *MockIController_GetClassByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIController_GetClassByID_Call) Return() *MockIController_GetClassByID_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIController_GetClassByID_Call) RunAndReturn(run func(c *gin.Context)) *MockIController_GetClassByID_Call {
	_c.Run(run)
	return _c
}

// GetClassBySystemID provides a mock function for the type MockIController
func (_mock *MockIController) GetClassBySystemID(c *gin.Context) {
	_mock.Called(c)
	return
}

// MockIController_GetClassBySystemID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClassBySystemID'
type MockIController_GetClassBySystemID_Call struct {
	*mock.Call
}

// GetClassBySystemID is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockIController_Expecter) GetClassBySystemID(c any) *MockIController_GetClassBySystemID_Call {
	return &MockIController_GetClassBySystemID_Call{Call: _e.mock.On("GetClassBySystemID", c)}
}

func (_c *MockIController_GetClassBySystemID_Call) Run(run func(c *gin.Context)) *MockIController_GetClassBySystemID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIController_GetClassBySystemID_Call) Return() *MockIController_GetClassBySystemID_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIController_GetClassBySystemID_Call) RunAndReturn(run func(c *gin.Context)) *MockIController_GetClassBySystemID_Call {
	_c.Run(run)
	return _c
}

// GetClasses provides a mock function for the type MockIController
func (_mock *MockIController) GetClasses(c *gin.Context) {
	_mock.Called(c)
	return
}

// MockIController_GetClasses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClasses'
type MockIController_GetClasses_Call struct {
	*mock.Call
}

// GetClasses is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockIController_Expecter) GetClasses(c any) *MockIController_GetClasses_Call {
	return &MockIController_GetClasses_Call{Call: _e.mock.On("GetClasses", c)}
}

func (_c *MockIController_GetClasses_Call) Run(run func(c *gin.Context)) *MockIController_GetClasses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIController_GetClasses_Call) Return() *MockIController_GetClasses_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIController_GetClasses_Call) RunAndReturn(run func(c *gin.Context)) *MockIController_GetClasses_Call {
	_c.Run(run)
	return _c
}

// UpdateClass provides a mock function for the type MockIController
func (_mock *MockIController) UpdateClass(c *gin.Context) {
	_mock.Called(c)
	return
}

// MockIController_UpdateClass_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateClass'
type MockIController_UpdateClass_Call struct {
	*mock.Call
}

// UpdateClass is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockIController_Expecter) UpdateClass(c any) *MockIController_UpdateClass_Call {
	return &MockIController_UpdateClass_Call{Call: _e.mock.On("UpdateClass", c)}
}

func (_c *MockIController_UpdateClass_Call) Run(run func(c *gin.Context)) *MockIController_UpdateClass_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIController_UpdateClass_Call) Return() *MockIController_UpdateClass_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIController_UpdateClass_Call) RunAndReturn(run func(c *gin.Context)) *MockIController_UpdateClass_Call {
	_c.Run(run)
	return _c
}

// NewMockIUseCase creates a new instance of MockIUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIUseCase {
	mock := &MockIUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIUseCase is an autogenerated mock type for the IUseCase type
type MockIUseCase struct {
	mock.Mock
}

type MockIUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIUseCase) EXPECT() *MockIUseCase_Expecter {
	return &MockIUseCase_Expecter{mock: &_m.Mock}
}

// CreateClass provides a mock function for the type MockIUseCase
func (_mock *MockIUseCase) CreateClass(ctx context.Context, data *class.CreateClassRequest) (*domain.Class, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateClass")
	}

	var r0 *domain.Class
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *class.CreateClassRequest) (*domain.Class, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *class.CreateClassRequest) *domain.Class); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Class)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *class.CreateClassRequest) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUseCase_CreateClass_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateClass'
type MockIUseCase_CreateClass_Call struct {
	*mock.Call
}

// CreateClass is a helper method to define mock.On call
//   - ctx context.Context
//   - data *class.CreateClassRequest
func (_e *MockIUseCase_Expecter) CreateClass(ctx any, data any) *MockIUseCase_CreateClass_Call {
	return &MockIUseCase_CreateClass_Call{Call: _e.mock.On("CreateClass", ctx, data)}
}

func (_c *MockIUseCase_CreateClass_Call) Run(run func(ctx context.Context, data *class.CreateClassRequest)) *MockIUseCase_CreateClass_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *class.CreateClassRequest
		if args[1] != nil {
			arg1 = args[1].(*class.CreateClassRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUseCase_CreateClass_Call) Return(class1 *domain.Class, err error) *MockIUseCase_CreateClass_Call {
	_c.Call.Return(class1, err)
	return _c
}

func (_c *MockIUseCase_CreateClass_Call) RunAndReturn(run func(ctx context.Context, data *class.CreateClassRequest) (*domain.Class, error)) *MockIUseCase_CreateClass_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteClass provides a mock function for the type MockIUseCase
func (_mock *MockIUseCase) DeleteClass(ctx context.Context, classID uuid.UUID) error {
	ret := _mock.Called(ctx, classID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteClass")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, classID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIUseCase_DeleteClass_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteClass'
type MockIUseCase_DeleteClass_Call struct {
	*mock.Call
}

// DeleteClass is a helper method to define mock.On call
//   - ctx context.Context
//   - classID uuid.UUID
func (_e *MockIUseCase_Expecter) DeleteClass(ctx any, classID any) *MockIUseCase_DeleteClass_Call {
	return &MockIUseCase_DeleteClass_Call{Call: _e.mock.On("DeleteClass", ctx, classID)}
}

func (_c *MockIUseCase_DeleteClass_Call) Run(run func(ctx context.Context, classID uuid.UUID)) *MockIUseCase_DeleteClass_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUseCase_DeleteClass_Call) Return(err error) *MockIUseCase_DeleteClass_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIUseCase_DeleteClass_Call) RunAndReturn(run func(ctx context.Context, classID uuid.UUID) error) *MockIUseCase_DeleteClass_Call {
	_c.Call.Return(run)
	return _c
}

// GetClassByID provides a mock function for the type MockIUseCase
func (_mock *MockIUseCase) GetClassByID(ctx context.Context, classID uuid.UUID) (*domain.Class, error) {
	ret := _mock.Called(ctx, classID)

	if len(ret) == 0 {
		panic("no return value specified for GetClassByID")
	}

	var r0 *domain.Class
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Class, error)); ok {
		return returnFunc(ctx, classID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Class); ok {
		r0 = returnFunc(ctx, classID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Class)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, classID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUseCase_GetClassByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClassByID'
type MockIUseCase_GetClassByID_Call struct {
	*mock.Call
}

// GetClassByID is a helper method to define mock.On call
//   - ctx context.Context
//   - classID uuid.UUID
func (_e *MockIUseCase_Expecter) GetClassByID(ctx any, classID any) *MockIUseCase_GetClassByID_Call {
	return &MockIUseCase_GetClassByID_Call{Call: _e.mock.On("GetClassByID", ctx, classID)}
}

func (_c *MockIUseCase_GetClassByID_Call) Run(run func(ctx context.Context, classID uuid.UUID)) *MockIUseCase_GetClassByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUseCase_GetClassByID_Call) Return(class1 *domain.Class, err error) *MockIUseCase_GetClassByID_Call {
	_c.Call.Return(class1, err)
	return _c
}

func (_c *MockIUseCase_GetClassByID_Call) RunAndReturn(run func(ctx context.Context, classID uuid.UUID) (*domain.Class, error)) *MockIUseCase_GetClassByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetClassBySystemID provides a mock function for the type MockIUseCase
func (_mock *MockIUseCase) GetClassBySystemID(ctx context.Context, systemID string) (*domain.Class, error) {
	ret := _mock.Called(ctx, systemID)

	if len(ret) == 0 {
		panic("no return value specified for GetClassBySystemID")
	}

	var r0 *domain.Class
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Class, error)); ok {
		return returnFunc(ctx, systemID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Class); ok {
		r0 = returnFunc(ctx, systemID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Class)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, systemID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUseCase_GetClassBySystemID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClassBySystemID'
type MockIUseCase_GetClassBySystemID_Call struct {
	*mock.Call
}

// GetClassBySystemID is a helper method to define mock.On call
//   - ctx context.Context
//   - systemID string
func (_e *MockIUseCase_Expecter) GetClassBySystemID(ctx any, systemID any) *MockIUseCase_GetClassBySystemID_Call {
	return &MockIUseCase_GetClassBySystemID_Call{Call: _e.mock.On("GetClassBySystemID", ctx, systemID)}
}

func (_c *MockIUseCase_GetClassBySystemID_Call) Run(run func(ctx context.Context, systemID string)) *MockIUseCase_GetClassBySystemID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUseCase_GetClassBySystemID_Call) Return(class1 *domain.Class, err error) *MockIUseCase_GetClassBySystemID_Call {
	_c.Call.Return(class1, err)
	return _c
}

func (_c *MockIUseCase_GetClassBySystemID_Call) RunAndReturn(run func(ctx context.Context, systemID string) (*domain.Class, error)) *MockIUseCase_GetClassBySystemID_Call {
	_c.Call.Return(run)
	return _c
}

// GetClasses provides a mock function for the type MockIUseCase
func (_mock *MockIUseCase) GetClasses(ctx context.Context) ([]*domain.Class, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetClasses")
	}

	var r0 []*domain.Class
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*domain.Class, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*domain.Class); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Class)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUseCase_GetClasses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClasses'
type MockIUseCase_GetClasses_Call struct {
	*mock.Call
}

// GetClasses is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIUseCase_Expecter) GetClasses(ctx any) *MockIUseCase_GetClasses_Call {
	return &MockIUseCase_GetClasses_Call{Call: _e.mock.On("GetClasses", ctx)}
}

func (_c *MockIUseCase_GetClasses_Call) Run(run func(ctx context.Context)) *MockIUseCase_GetClasses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIUseCase_GetClasses_Call) Return(classs []*domain.Class, err error) *MockIUseCase_GetClasses_Call {
	_c.Call.Return(classs, err)
	return _c
}

func (_c *MockIUseCase_GetClasses_Call) RunAndReturn(run func(ctx context.Context) ([]*domain.Class, error)) *MockIUseCase_GetClasses_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateClass provides a mock function for the type MockIUseCase
func (_mock *MockIUseCase) UpdateClass(ctx context.Context, data *class.UpdateClassDTO) (*domain.Class, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateClass")
	}

	var r0 *domain.Class
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *class.UpdateClassDTO) (*domain.Class, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *class.UpdateClassDTO) *domain.Class); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Class)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *class.UpdateClassDTO) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUseCase_UpdateClass_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateClass'
type MockIUseCase_UpdateClass_Call struct {
	*mock.Call
}

// UpdateClass is a helper method to define mock.On call
//   - ctx context.Context
//   - data *class.UpdateClassDTO
func (_e *MockIUseCase_Expecter) UpdateClass(ctx any, data any) *MockIUseCase_UpdateClass_Call {
	return &MockIUseCase_UpdateClass_Call{Call: _e.mock.On("UpdateClass", ctx, data)}
}

func (_c *MockIUseCase_UpdateClass_Call) Run(run func(ctx context.Context, data *class.UpdateClassDTO)) *MockIUseCase_UpdateClass_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *class.UpdateClassDTO
		if args[1] != nil {
			arg1 = args[1].(*class.UpdateClassDTO)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUseCase_UpdateClass_Call) Return(class1 *domain.Class, err error) *MockIUseCase_UpdateClass_Call {
	_c.Call.Return(class1, err)
	return _c
}

func (_c *MockIUseCase_UpdateClass_Call) RunAndReturn(run func(ctx context.Context, data *class.UpdateClassDTO) (*domain.Class, error)) *MockIUseCase_UpdateClass_Call {
	_c.Call.Return(run)
	return _c
}
