// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth_mocks

import (
	"context"
	"main/internal/domain"
	"main/internal/modules/auth"

	"github.com/gin-gonic/gin"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIController creates a new instance of MockIController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIController(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIController {
	mock := &MockIController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIController is an autogenerated mock type for the IController type
type MockIController struct {
	mock.Mock
}

type MockIController_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIController) EXPECT() *MockIController_Expecter {
	return &MockIController_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type MockIController
func (_mock *MockIController) Login(c *gin.Context) {
	_mock.Called(c)
	return
}

// MockIController_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockIController_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockIController_Expecter) Login(c any) *MockIController_Login_Call {
	return &MockIController_Login_Call{Call: _e.mock.On("Login", c)}
}

func (_c *MockIController_Login_Call) Run(run func(c *gin.Context)) *MockIController_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIController_Login_Call) Return() *MockIController_Login_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIController_Login_Call) RunAndReturn(run func(c *gin.Context)) *MockIController_Login_Call {
	_c.Run(run)
	return _c
}

// Logout provides a mock function for the type MockIController
func (_mock *MockIController) Logout(c *gin.Context) {
	_mock.Called(c)
	return
}

// MockIController_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockIController_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockIController_Expecter) Logout(c any) *MockIController_Logout_Call {
	return &MockIController_Logout_Call{Call: _e.mock.On("Logout", c)}
}

func (_c *MockIController_Logout_Call) Run(run func(c *gin.Context)) *MockIController_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIController_Logout_Call) Return() *MockIController_Logout_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIController_Logout_Call) RunAndReturn(run func(c *gin.Context)) *MockIController_Logout_Call {
	_c.Run(run)
	return _c
}

// Refresh provides a mock function for the type MockIController
func (_mock *MockIController) Refresh(c *gin.Context) {
	_mock.Called(c)
	return
}

// MockIController_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type MockIController_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockIController_Expecter) Refresh(c any) *MockIController_Refresh_Call {
	return &MockIController_Refresh_Call{Call: _e.mock.On("Refresh", c)}
}

func (_c *MockIController_Refresh_Call) Run(run func(c *gin.Context)) *MockIController_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIController_Refresh_Call) Return() *MockIController_Refresh_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIController_Refresh_Call) RunAndReturn(run func(c *gin.Context)) *MockIController_Refresh_Call {
	_c.Run(run)
	return _c
}

// NewMockIRepository creates a new instance of MockIRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRepository {
	mock := &MockIRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIRepository is an autogenerated mock type for the IRepository type
type MockIRepository struct {
	mock.Mock
}

type MockIRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRepository) EXPECT() *MockIRepository_Expecter {
	return &MockIRepository_Expecter{mock: &_m.Mock}
}

// CreateJWT provides a mock function for the type MockIRepository
func (_mock *MockIRepository) CreateJWT(ctx context.Context, JWTPayload *domain.JWTPayload, token string) (*string, error) {
	ret := _mock.Called(ctx, JWTPayload, token)

	if len(ret) == 0 {
		panic("no return value specified for CreateJWT")
	}

	var r0 *string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.JWTPayload, string) (*string, error)); ok {
		return returnFunc(ctx, JWTPayload, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.JWTPayload, string) *string); ok {
		r0 = returnFunc(ctx, JWTPayload, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.JWTPayload, string) error); ok {
		r1 = returnFunc(ctx, JWTPayload, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRepository_CreateJWT_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateJWT'
type MockIRepository_CreateJWT_Call struct {
	*mock.Call
}

// CreateJWT is a helper method to define mock.On call
//   - ctx context.Context
//   - JWTPayload *domain.JWTPayload
//   - token string
func (_e *MockIRepository_Expecter) CreateJWT(ctx any, JWTPayload any, token any) *MockIRepository_CreateJWT_Call {
	return &MockIRepository_CreateJWT_Call{Call: _e.mock.On("CreateJWT", ctx, JWTPayload, token)}
}

func (_c *MockIRepository_CreateJWT_Call) Run(run func(ctx context.Context, JWTPayload *domain.JWTPayload, token string)) *MockIRepository_CreateJWT_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.JWTPayload
		if args[1] != nil {
			arg1 = args[1].(*domain.JWTPayload)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIRepository_CreateJWT_Call) Return(s *string, err error) *MockIRepository_CreateJWT_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockIRepository_CreateJWT_Call) RunAndReturn(run func(ctx context.Context, JWTPayload *domain.JWTPayload, token string) (*string, error)) *MockIRepository_CreateJWT_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteJWT provides a mock function for the type MockIRepository
func (_mock *MockIRepository) DeleteJWT(ctx context.Context, ID uuid.UUID) error {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteJWT")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIRepository_DeleteJWT_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteJWT'
type MockIRepository_DeleteJWT_Call struct {
	*mock.Call
}

// DeleteJWT is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
func (_e *MockIRepository_Expecter) DeleteJWT(ctx any, ID any) *MockIRepository_DeleteJWT_Call {
	return &MockIRepository_DeleteJWT_Call{Call: _e.mock.On("DeleteJWT", ctx, ID)}
}

func (_c *MockIRepository_DeleteJWT_Call) Run(run func(ctx context.Context, ID uuid.UUID)) *MockIRepository_DeleteJWT_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIRepository_DeleteJWT_Call) Return(err error) *MockIRepository_DeleteJWT_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIRepository_DeleteJWT_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID) error) *MockIRepository_DeleteJWT_Call {
	_c.Call.Return(run)
	return _c
}

// FindJWT provides a mock function for the type MockIRepository
func (_mock *MockIRepository) FindJWT(ctx context.Context, JTI uuid.UUID) (*string, error) {
	ret := _mock.Called(ctx, JTI)

	if len(ret) == 0 {
		panic("no return value specified for FindJWT")
	}

	var r0 *string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*string, error)); ok {
		return returnFunc(ctx, JTI)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *string); ok {
		r0 = returnFunc(ctx, JTI)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, JTI)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRepository_FindJWT_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindJWT'
type MockIRepository_FindJWT_Call struct {
	*mock.Call
}

// FindJWT is a helper method to define mock.On call
//   - ctx context.Context
//   - JTI uuid.UUID
func (_e *MockIRepository_Expecter) FindJWT(ctx any, JTI any) *MockIRepository_FindJWT_Call {
	return &MockIRepository_FindJWT_Call{Call: _e.mock.On("FindJWT", ctx, JTI)}
}

func (_c *MockIRepository_FindJWT_Call) Run(run func(ctx context.Context, JTI uuid.UUID)) *MockIRepository_FindJWT_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIRepository_FindJWT_Call) Return(s *string, err error) *MockIRepository_FindJWT_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockIRepository_FindJWT_Call) RunAndReturn(run func(ctx context.Context, JTI uuid.UUID) (*string, error)) *MockIRepository_FindJWT_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIUseCase creates a new instance of MockIUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIUseCase {
	mock := &MockIUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIUseCase is an autogenerated mock type for the IUseCase type
type MockIUseCase struct {
	mock.Mock
}

type MockIUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIUseCase) EXPECT() *MockIUseCase_Expecter {
	return &MockIUseCase_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type MockIUseCase
func (_mock *MockIUseCase) Login(ctx context.Context, data *auth.LoginSchema) (*auth.Tokens, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *auth.Tokens
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.LoginSchema) (*auth.Tokens, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.LoginSchema) *auth.Tokens); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.Tokens)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *auth.LoginSchema) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUseCase_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockIUseCase_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - data *auth.LoginSchema
func (_e *MockIUseCase_Expecter) Login(ctx any, data any) *MockIUseCase_Login_Call {
	return &MockIUseCase_Login_Call{Call: _e.mock.On("Login", ctx, data)}
}

func (_c *MockIUseCase_Login_Call) Run(run func(ctx context.Context, data *auth.LoginSchema)) *MockIUseCase_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auth.LoginSchema
		if args[1] != nil {
			arg1 = args[1].(*auth.LoginSchema)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUseCase_Login_Call) Return(tokens *auth.Tokens, err error) *MockIUseCase_Login_Call {
	_c.Call.Return(tokens, err)
	return _c
}

func (_c *MockIUseCase_Login_Call) RunAndReturn(run func(ctx context.Context, data *auth.LoginSchema) (*auth.Tokens, error)) *MockIUseCase_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function for the type MockIUseCase
func (_mock *MockIUseCase) Logout(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIUseCase_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockIUseCase_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockIUseCase_Expecter) Logout(ctx any, id any) *MockIUseCase_Logout_Call {
	return &MockIUseCase_Logout_Call{Call: _e.mock.On("Logout", ctx, id)}
}

func (_c *MockIUseCase_Logout_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockIUseCase_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUseCase_Logout_Call) Return(err error) *MockIUseCase_Logout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIUseCase_Logout_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockIUseCase_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// Recover provides a mock function for the type MockIUseCase
func (_mock *MockIUseCase) Recover(ctx context.Context, data *auth.RecoverSchema) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Recover")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.RecoverSchema) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIUseCase_Recover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Recover'
type MockIUseCase_Recover_Call struct {
	*mock.Call
}

// Recover is a helper method to define mock.On call
//   - ctx context.Context
//   - data *auth.RecoverSchema
func (_e *MockIUseCase_Expecter) Recover(ctx any, data any) *MockIUseCase_Recover_Call {
	return &MockIUseCase_Recover_Call{Call: _e.mock.On("Recover", ctx, data)}
}

func (_c *MockIUseCase_Recover_Call) Run(run func(ctx context.Context, data *auth.RecoverSchema)) *MockIUseCase_Recover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auth.RecoverSchema
		if args[1] != nil {
			arg1 = args[1].(*auth.RecoverSchema)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUseCase_Recover_Call) Return(err error) *MockIUseCase_Recover_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIUseCase_Recover_Call) RunAndReturn(run func(ctx context.Context, data *auth.RecoverSchema) error) *MockIUseCase_Recover_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function for the type MockIUseCase
func (_mock *MockIUseCase) Refresh(ctx context.Context, JWTPayload *domain.JWTPayload) (*auth.Tokens, error) {
	ret := _mock.Called(ctx, JWTPayload)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 *auth.Tokens
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.JWTPayload) (*auth.Tokens, error)); ok {
		return returnFunc(ctx, JWTPayload)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.JWTPayload) *auth.Tokens); ok {
		r0 = returnFunc(ctx, JWTPayload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.Tokens)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.JWTPayload) error); ok {
		r1 = returnFunc(ctx, JWTPayload)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUseCase_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type MockIUseCase_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
//   - JWTPayload *domain.JWTPayload
func (_e *MockIUseCase_Expecter) Refresh(ctx any, JWTPayload any) *MockIUseCase_Refresh_Call {
	return &MockIUseCase_Refresh_Call{Call: _e.mock.On("Refresh", ctx, JWTPayload)}
}

func (_c *MockIUseCase_Refresh_Call) Run(run func(ctx context.Context, JWTPayload *domain.JWTPayload)) *MockIUseCase_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.JWTPayload
		if args[1] != nil {
			arg1 = args[1].(*domain.JWTPayload)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUseCase_Refresh_Call) Return(tokens *auth.Tokens, err error) *MockIUseCase_Refresh_Call {
	_c.Call.Return(tokens, err)
	return _c
}

func (_c *MockIUseCase_Refresh_Call) RunAndReturn(run func(ctx context.Context, JWTPayload *domain.JWTPayload) (*auth.Tokens, error)) *MockIUseCase_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyRecovery provides a mock function for the type MockIUseCase
func (_mock *MockIUseCase) VerifyRecovery(ctx context.Context, data *auth.VerifyRecoverSchema) (*domain.User, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for VerifyRecovery")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.VerifyRecoverSchema) (*domain.User, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.VerifyRecoverSchema) *domain.User); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *auth.VerifyRecoverSchema) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUseCase_VerifyRecovery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyRecovery'
type MockIUseCase_VerifyRecovery_Call struct {
	*mock.Call
}

// VerifyRecovery is a helper method to define mock.On call
//   - ctx context.Context
//   - data *auth.VerifyRecoverSchema
func (_e *MockIUseCase_Expecter) VerifyRecovery(ctx any, data any) *MockIUseCase_VerifyRecovery_Call {
	return &MockIUseCase_VerifyRecovery_Call{Call: _e.mock.On("VerifyRecovery", ctx, data)}
}

func (_c *MockIUseCase_VerifyRecovery_Call) Run(run func(ctx context.Context, data *auth.VerifyRecoverSchema)) *MockIUseCase_VerifyRecovery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auth.VerifyRecoverSchema
		if args[1] != nil {
			arg1 = args[1].(*auth.VerifyRecoverSchema)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUseCase_VerifyRecovery_Call) Return(user *domain.User, err error) *MockIUseCase_VerifyRecovery_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockIUseCase_VerifyRecovery_Call) RunAndReturn(run func(ctx context.Context, data *auth.VerifyRecoverSchema) (*domain.User, error)) *MockIUseCase_VerifyRecovery_Call {
	_c.Call.Return(run)
	return _c
}
