// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package pkg_mocks

import (
	"context"
	"main/internal/domain"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockHasher creates a new instance of MockHasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHasher {
	mock := &MockHasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHasher is an autogenerated mock type for the Hasher type
type MockHasher struct {
	mock.Mock
}

type MockHasher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHasher) EXPECT() *MockHasher_Expecter {
	return &MockHasher_Expecter{mock: &_m.Mock}
}

// Compare provides a mock function for the type MockHasher
func (_mock *MockHasher) Compare(hashed string, literal string) error {
	ret := _mock.Called(hashed, literal)

	if len(ret) == 0 {
		panic("no return value specified for Compare")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(hashed, literal)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHasher_Compare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Compare'
type MockHasher_Compare_Call struct {
	*mock.Call
}

// Compare is a helper method to define mock.On call
//   - hashed string
//   - literal string
func (_e *MockHasher_Expecter) Compare(hashed any, literal any) *MockHasher_Compare_Call {
	return &MockHasher_Compare_Call{Call: _e.mock.On("Compare", hashed, literal)}
}

func (_c *MockHasher_Compare_Call) Run(run func(hashed string, literal string)) *MockHasher_Compare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHasher_Compare_Call) Return(err error) *MockHasher_Compare_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHasher_Compare_Call) RunAndReturn(run func(hashed string, literal string) error) *MockHasher_Compare_Call {
	_c.Call.Return(run)
	return _c
}

// Hash provides a mock function for the type MockHasher
func (_mock *MockHasher) Hash(literal string) ([]byte, error) {
	ret := _mock.Called(literal)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(literal)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(literal)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(literal)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHasher_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type MockHasher_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - literal string
func (_e *MockHasher_Expecter) Hash(literal any) *MockHasher_Hash_Call {
	return &MockHasher_Hash_Call{Call: _e.mock.On("Hash", literal)}
}

func (_c *MockHasher_Hash_Call) Run(run func(literal string)) *MockHasher_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHasher_Hash_Call) Return(bytes []byte, err error) *MockHasher_Hash_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockHasher_Hash_Call) RunAndReturn(run func(literal string) ([]byte, error)) *MockHasher_Hash_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLogger creates a new instance of MockLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogger {
	mock := &MockLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLogger is an autogenerated mock type for the Logger type
type MockLogger struct {
	mock.Mock
}

type MockLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogger) EXPECT() *MockLogger_Expecter {
	return &MockLogger_Expecter{mock: &_m.Mock}
}

// Error provides a mock function for the type MockLogger
func (_mock *MockLogger) Error(msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(msg, args)
	} else {
		_mock.Called(msg)
	}

	return
}

// MockLogger_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockLogger_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - msg string
//   - args ...any
func (_e *MockLogger_Expecter) Error(msg any, args ...any) *MockLogger_Error_Call {
	return &MockLogger_Error_Call{Call: _e.mock.On("Error",
		append([]any{msg}, args...)...)}
}

func (_c *MockLogger_Error_Call) Run(run func(msg string, args ...any)) *MockLogger_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Error_Call) Return() *MockLogger_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Error_Call) RunAndReturn(run func(msg string, args ...any)) *MockLogger_Error_Call {
	_c.Run(run)
	return _c
}

// ErrorLog provides a mock function for the type MockLogger
func (_mock *MockLogger) ErrorLog(method string, path string, statusCode int, err error) {
	_mock.Called(method, path, statusCode, err)
	return
}

// MockLogger_ErrorLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ErrorLog'
type MockLogger_ErrorLog_Call struct {
	*mock.Call
}

// ErrorLog is a helper method to define mock.On call
//   - method string
//   - path string
//   - statusCode int
//   - err error
func (_e *MockLogger_Expecter) ErrorLog(method any, path any, statusCode any, err any) *MockLogger_ErrorLog_Call {
	return &MockLogger_ErrorLog_Call{Call: _e.mock.On("ErrorLog", method, path, statusCode, err)}
}

func (_c *MockLogger_ErrorLog_Call) Run(run func(method string, path string, statusCode int, err error)) *MockLogger_ErrorLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 error
		if args[3] != nil {
			arg3 = args[3].(error)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockLogger_ErrorLog_Call) Return() *MockLogger_ErrorLog_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_ErrorLog_Call) RunAndReturn(run func(method string, path string, statusCode int, err error)) *MockLogger_ErrorLog_Call {
	_c.Run(run)
	return _c
}

// Info provides a mock function for the type MockLogger
func (_mock *MockLogger) Info(msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(msg, args)
	} else {
		_mock.Called(msg)
	}

	return
}

// MockLogger_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockLogger_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - msg string
//   - args ...any
func (_e *MockLogger_Expecter) Info(msg any, args ...any) *MockLogger_Info_Call {
	return &MockLogger_Info_Call{Call: _e.mock.On("Info",
		append([]any{msg}, args...)...)}
}

func (_c *MockLogger_Info_Call) Run(run func(msg string, args ...any)) *MockLogger_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Info_Call) Return() *MockLogger_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Info_Call) RunAndReturn(run func(msg string, args ...any)) *MockLogger_Info_Call {
	_c.Run(run)
	return _c
}

// RequestLog provides a mock function for the type MockLogger
func (_mock *MockLogger) RequestLog(requestID string, method string, path string, statusCode int, start time.Time) {
	_mock.Called(requestID, method, path, statusCode, start)
	return
}

// MockLogger_RequestLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestLog'
type MockLogger_RequestLog_Call struct {
	*mock.Call
}

// RequestLog is a helper method to define mock.On call
//   - requestID string
//   - method string
//   - path string
//   - statusCode int
//   - start time.Time
func (_e *MockLogger_Expecter) RequestLog(requestID any, method any, path any, statusCode any, start any) *MockLogger_RequestLog_Call {
	return &MockLogger_RequestLog_Call{Call: _e.mock.On("RequestLog", requestID, method, path, statusCode, start)}
}

func (_c *MockLogger_RequestLog_Call) Run(run func(requestID string, method string, path string, statusCode int, start time.Time)) *MockLogger_RequestLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockLogger_RequestLog_Call) Return() *MockLogger_RequestLog_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_RequestLog_Call) RunAndReturn(run func(requestID string, method string, path string, statusCode int, start time.Time)) *MockLogger_RequestLog_Call {
	_c.Run(run)
	return _c
}

// Warn provides a mock function for the type MockLogger
func (_mock *MockLogger) Warn(msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(msg, args)
	} else {
		_mock.Called(msg)
	}

	return
}

// MockLogger_Warn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warn'
type MockLogger_Warn_Call struct {
	*mock.Call
}

// Warn is a helper method to define mock.On call
//   - msg string
//   - args ...any
func (_e *MockLogger_Expecter) Warn(msg any, args ...any) *MockLogger_Warn_Call {
	return &MockLogger_Warn_Call{Call: _e.mock.On("Warn",
		append([]any{msg}, args...)...)}
}

func (_c *MockLogger_Warn_Call) Run(run func(msg string, args ...any)) *MockLogger_Warn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Warn_Call) Return() *MockLogger_Warn_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Warn_Call) RunAndReturn(run func(msg string, args ...any)) *MockLogger_Warn_Call {
	_c.Run(run)
	return _c
}

// WarnSkip provides a mock function for the type MockLogger
func (_mock *MockLogger) WarnSkip(skip int, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(skip, msg, args)
	} else {
		_mock.Called(skip, msg)
	}

	return
}

// MockLogger_WarnSkip_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WarnSkip'
type MockLogger_WarnSkip_Call struct {
	*mock.Call
}

// WarnSkip is a helper method to define mock.On call
//   - skip int
//   - msg string
//   - args ...any
func (_e *MockLogger_Expecter) WarnSkip(skip any, msg any, args ...any) *MockLogger_WarnSkip_Call {
	return &MockLogger_WarnSkip_Call{Call: _e.mock.On("WarnSkip",
		append([]any{skip, msg}, args...)...)}
}

func (_c *MockLogger_WarnSkip_Call) Run(run func(skip int, msg string, args ...any)) *MockLogger_WarnSkip_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockLogger_WarnSkip_Call) Return() *MockLogger_WarnSkip_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_WarnSkip_Call) RunAndReturn(run func(skip int, msg string, args ...any)) *MockLogger_WarnSkip_Call {
	_c.Run(run)
	return _c
}

// NewMockMailer creates a new instance of MockMailer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMailer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMailer {
	mock := &MockMailer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMailer is an autogenerated mock type for the Mailer type
type MockMailer struct {
	mock.Mock
}

type MockMailer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMailer) EXPECT() *MockMailer_Expecter {
	return &MockMailer_Expecter{mock: &_m.Mock}
}

// Send provides a mock function for the type MockMailer
func (_mock *MockMailer) Send(ctx context.Context, to string, subject string, html string) error {
	ret := _mock.Called(ctx, to, subject, html)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, to, subject, html)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMailer_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockMailer_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - to string
//   - subject string
//   - html string
func (_e *MockMailer_Expecter) Send(ctx any, to any, subject any, html any) *MockMailer_Send_Call {
	return &MockMailer_Send_Call{Call: _e.mock.On("Send", ctx, to, subject, html)}
}

func (_c *MockMailer_Send_Call) Run(run func(ctx context.Context, to string, subject string, html string)) *MockMailer_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMailer_Send_Call) Return(err error) *MockMailer_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMailer_Send_Call) RunAndReturn(run func(ctx context.Context, to string, subject string, html string) error) *MockMailer_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockObjectStorage creates a new instance of MockObjectStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObjectStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObjectStorage {
	mock := &MockObjectStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockObjectStorage is an autogenerated mock type for the ObjectStorage type
type MockObjectStorage struct {
	mock.Mock
}

type MockObjectStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockObjectStorage) EXPECT() *MockObjectStorage_Expecter {
	return &MockObjectStorage_Expecter{mock: &_m.Mock}
}

// UploadFile provides a mock function for the type MockObjectStorage
func (_mock *MockObjectStorage) UploadFile(ctx context.Context, bucketName string, objectName string, contentType string, file []byte) (*domain.File, error) {
	ret := _mock.Called(ctx, bucketName, objectName, contentType, file)

	if len(ret) == 0 {
		panic("no return value specified for UploadFile")
	}

	var r0 *domain.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, []byte) (*domain.File, error)); ok {
		return returnFunc(ctx, bucketName, objectName, contentType, file)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, []byte) *domain.File); ok {
		r0 = returnFunc(ctx, bucketName, objectName, contentType, file)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, []byte) error); ok {
		r1 = returnFunc(ctx, bucketName, objectName, contentType, file)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockObjectStorage_UploadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadFile'
type MockObjectStorage_UploadFile_Call struct {
	*mock.Call
}

// UploadFile is a helper method to define mock.On call
//   - ctx context.Context
//   - bucketName string
//   - objectName string
//   - contentType string
//   - file []byte
func (_e *MockObjectStorage_Expecter) UploadFile(ctx any, bucketName any, objectName any, contentType any, file any) *MockObjectStorage_UploadFile_Call {
	return &MockObjectStorage_UploadFile_Call{Call: _e.mock.On("UploadFile", ctx, bucketName, objectName, contentType, file)}
}

func (_c *MockObjectStorage_UploadFile_Call) Run(run func(ctx context.Context, bucketName string, objectName string, contentType string, file []byte)) *MockObjectStorage_UploadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []byte
		if args[4] != nil {
			arg4 = args[4].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockObjectStorage_UploadFile_Call) Return(file1 *domain.File, err error) *MockObjectStorage_UploadFile_Call {
	_c.Call.Return(file1, err)
	return _c
}

func (_c *MockObjectStorage_UploadFile_Call) RunAndReturn(run func(ctx context.Context, bucketName string, objectName string, contentType string, file []byte) (*domain.File, error)) *MockObjectStorage_UploadFile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRedisClient creates a new instance of MockRedisClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRedisClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRedisClient {
	mock := &MockRedisClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRedisClient is an autogenerated mock type for the RedisClient type
type MockRedisClient struct {
	mock.Mock
}

type MockRedisClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRedisClient) EXPECT() *MockRedisClient_Expecter {
	return &MockRedisClient_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockRedisClient
func (_mock *MockRedisClient) Delete(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRedisClient_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRedisClient_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockRedisClient_Expecter) Delete(ctx any, key any) *MockRedisClient_Delete_Call {
	return &MockRedisClient_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockRedisClient_Delete_Call) Run(run func(ctx context.Context, key string)) *MockRedisClient_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRedisClient_Delete_Call) Return(err error) *MockRedisClient_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRedisClient_Delete_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockRedisClient_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockRedisClient
func (_mock *MockRedisClient) Get(ctx context.Context, key string) (string, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRedisClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRedisClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockRedisClient_Expecter) Get(ctx any, key any) *MockRedisClient_Get_Call {
	return &MockRedisClient_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockRedisClient_Get_Call) Run(run func(ctx context.Context, key string)) *MockRedisClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRedisClient_Get_Call) Return(s string, err error) *MockRedisClient_Get_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockRedisClient_Get_Call) RunAndReturn(run func(ctx context.Context, key string) (string, error)) *MockRedisClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockRedisClient
func (_mock *MockRedisClient) Set(ctx context.Context, key string, value any, expiration time.Duration) error {
	ret := _mock.Called(ctx, key, value, expiration)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, time.Duration) error); ok {
		r0 = returnFunc(ctx, key, value, expiration)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRedisClient_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockRedisClient_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value any
//   - expiration time.Duration
func (_e *MockRedisClient_Expecter) Set(ctx any, key any, value any, expiration any) *MockRedisClient_Set_Call {
	return &MockRedisClient_Set_Call{Call: _e.mock.On("Set", ctx, key, value, expiration)}
}

func (_c *MockRedisClient_Set_Call) Run(run func(ctx context.Context, key string, value any, expiration time.Duration)) *MockRedisClient_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRedisClient_Set_Call) Return(err error) *MockRedisClient_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRedisClient_Set_Call) RunAndReturn(run func(ctx context.Context, key string, value any, expiration time.Duration) error) *MockRedisClient_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenService creates a new instance of MockTokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenService {
	mock := &MockTokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenService is an autogenerated mock type for the TokenService type
type MockTokenService struct {
	mock.Mock
}

type MockTokenService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenService) EXPECT() *MockTokenService_Expecter {
	return &MockTokenService_Expecter{mock: &_m.Mock}
}

// Compare provides a mock function for the type MockTokenService
func (_mock *MockTokenService) Compare(hashed string, literal string) bool {
	ret := _mock.Called(hashed, literal)

	if len(ret) == 0 {
		panic("no return value specified for Compare")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = returnFunc(hashed, literal)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockTokenService_Compare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Compare'
type MockTokenService_Compare_Call struct {
	*mock.Call
}

// Compare is a helper method to define mock.On call
//   - hashed string
//   - literal string
func (_e *MockTokenService_Expecter) Compare(hashed any, literal any) *MockTokenService_Compare_Call {
	return &MockTokenService_Compare_Call{Call: _e.mock.On("Compare", hashed, literal)}
}

func (_c *MockTokenService_Compare_Call) Run(run func(hashed string, literal string)) *MockTokenService_Compare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenService_Compare_Call) Return(b bool) *MockTokenService_Compare_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockTokenService_Compare_Call) RunAndReturn(run func(hashed string, literal string) bool) *MockTokenService_Compare_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateAccessToken provides a mock function for the type MockTokenService
func (_mock *MockTokenService) GenerateAccessToken(data *domain.User) (*domain.JWT, error) {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAccessToken")
	}

	var r0 *domain.JWT
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*domain.User) (*domain.JWT, error)); ok {
		return returnFunc(data)
	}
	if returnFunc, ok := ret.Get(0).(func(*domain.User) *domain.JWT); ok {
		r0 = returnFunc(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.JWT)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*domain.User) error); ok {
		r1 = returnFunc(data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenService_GenerateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateAccessToken'
type MockTokenService_GenerateAccessToken_Call struct {
	*mock.Call
}

// GenerateAccessToken is a helper method to define mock.On call
//   - data *domain.User
func (_e *MockTokenService_Expecter) GenerateAccessToken(data any) *MockTokenService_GenerateAccessToken_Call {
	return &MockTokenService_GenerateAccessToken_Call{Call: _e.mock.On("GenerateAccessToken", data)}
}

func (_c *MockTokenService_GenerateAccessToken_Call) Run(run func(data *domain.User)) *MockTokenService_GenerateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *domain.User
		if args[0] != nil {
			arg0 = args[0].(*domain.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenService_GenerateAccessToken_Call) Return(jWT *domain.JWT, err error) *MockTokenService_GenerateAccessToken_Call {
	_c.Call.Return(jWT, err)
	return _c
}

func (_c *MockTokenService_GenerateAccessToken_Call) RunAndReturn(run func(data *domain.User) (*domain.JWT, error)) *MockTokenService_GenerateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateRefreshToken provides a mock function for the type MockTokenService
func (_mock *MockTokenService) GenerateRefreshToken(data *domain.User) (*domain.JWT, error) {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for GenerateRefreshToken")
	}

	var r0 *domain.JWT
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*domain.User) (*domain.JWT, error)); ok {
		return returnFunc(data)
	}
	if returnFunc, ok := ret.Get(0).(func(*domain.User) *domain.JWT); ok {
		r0 = returnFunc(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.JWT)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*domain.User) error); ok {
		r1 = returnFunc(data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenService_GenerateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateRefreshToken'
type MockTokenService_GenerateRefreshToken_Call struct {
	*mock.Call
}

// GenerateRefreshToken is a helper method to define mock.On call
//   - data *domain.User
func (_e *MockTokenService_Expecter) GenerateRefreshToken(data any) *MockTokenService_GenerateRefreshToken_Call {
	return &MockTokenService_GenerateRefreshToken_Call{Call: _e.mock.On("GenerateRefreshToken", data)}
}

func (_c *MockTokenService_GenerateRefreshToken_Call) Run(run func(data *domain.User)) *MockTokenService_GenerateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *domain.User
		if args[0] != nil {
			arg0 = args[0].(*domain.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenService_GenerateRefreshToken_Call) Return(jWT *domain.JWT, err error) *MockTokenService_GenerateRefreshToken_Call {
	_c.Call.Return(jWT, err)
	return _c
}

func (_c *MockTokenService_GenerateRefreshToken_Call) RunAndReturn(run func(data *domain.User) (*domain.JWT, error)) *MockTokenService_GenerateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// HashToken provides a mock function for the type MockTokenService
func (_mock *MockTokenService) HashToken(tokenString string) string {
	ret := _mock.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for HashToken")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(tokenString)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTokenService_HashToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashToken'
type MockTokenService_HashToken_Call struct {
	*mock.Call
}

// HashToken is a helper method to define mock.On call
//   - tokenString string
func (_e *MockTokenService_Expecter) HashToken(tokenString any) *MockTokenService_HashToken_Call {
	return &MockTokenService_HashToken_Call{Call: _e.mock.On("HashToken", tokenString)}
}

func (_c *MockTokenService_HashToken_Call) Run(run func(tokenString string)) *MockTokenService_HashToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenService_HashToken_Call) Return(s string) *MockTokenService_HashToken_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTokenService_HashToken_Call) RunAndReturn(run func(tokenString string) string) *MockTokenService_HashToken_Call {
	_c.Call.Return(run)
	return _c
}

// ParseAccessToken provides a mock function for the type MockTokenService
func (_mock *MockTokenService) ParseAccessToken(tokenString string) (*domain.JWTPayload, error) {
	ret := _mock.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for ParseAccessToken")
	}

	var r0 *domain.JWTPayload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*domain.JWTPayload, error)); ok {
		return returnFunc(tokenString)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *domain.JWTPayload); ok {
		r0 = returnFunc(tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.JWTPayload)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(tokenString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenService_ParseAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseAccessToken'
type MockTokenService_ParseAccessToken_Call struct {
	*mock.Call
}

// ParseAccessToken is a helper method to define mock.On call
//   - tokenString string
func (_e *MockTokenService_Expecter) ParseAccessToken(tokenString any) *MockTokenService_ParseAccessToken_Call {
	return &MockTokenService_ParseAccessToken_Call{Call: _e.mock.On("ParseAccessToken", tokenString)}
}

func (_c *MockTokenService_ParseAccessToken_Call) Run(run func(tokenString string)) *MockTokenService_ParseAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenService_ParseAccessToken_Call) Return(jWTPayload *domain.JWTPayload, err error) *MockTokenService_ParseAccessToken_Call {
	_c.Call.Return(jWTPayload, err)
	return _c
}

func (_c *MockTokenService_ParseAccessToken_Call) RunAndReturn(run func(tokenString string) (*domain.JWTPayload, error)) *MockTokenService_ParseAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// ParseRefreshToken provides a mock function for the type MockTokenService
func (_mock *MockTokenService) ParseRefreshToken(tokenString string) (*domain.JWTPayload, error) {
	ret := _mock.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for ParseRefreshToken")
	}

	var r0 *domain.JWTPayload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*domain.JWTPayload, error)); ok {
		return returnFunc(tokenString)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *domain.JWTPayload); ok {
		r0 = returnFunc(tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.JWTPayload)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(tokenString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenService_ParseRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseRefreshToken'
type MockTokenService_ParseRefreshToken_Call struct {
	*mock.Call
}

// ParseRefreshToken is a helper method to define mock.On call
//   - tokenString string
func (_e *MockTokenService_Expecter) ParseRefreshToken(tokenString any) *MockTokenService_ParseRefreshToken_Call {
	return &MockTokenService_ParseRefreshToken_Call{Call: _e.mock.On("ParseRefreshToken", tokenString)}
}

func (_c *MockTokenService_ParseRefreshToken_Call) Run(run func(tokenString string)) *MockTokenService_ParseRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenService_ParseRefreshToken_Call) Return(jWTPayload *domain.JWTPayload, err error) *MockTokenService_ParseRefreshToken_Call {
	_c.Call.Return(jWTPayload, err)
	return _c
}

func (_c *MockTokenService_ParseRefreshToken_Call) RunAndReturn(run func(tokenString string) (*domain.JWTPayload, error)) *MockTokenService_ParseRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}
