// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package pkg_mocks

import (
	"context"
	"main/internal/domain"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockBcryptHasher creates a new instance of MockBcryptHasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBcryptHasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBcryptHasher {
	mock := &MockBcryptHasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBcryptHasher is an autogenerated mock type for the BcryptHasher type
type MockBcryptHasher struct {
	mock.Mock
}

type MockBcryptHasher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBcryptHasher) EXPECT() *MockBcryptHasher_Expecter {
	return &MockBcryptHasher_Expecter{mock: &_m.Mock}
}

// Compare provides a mock function for the type MockBcryptHasher
func (_mock *MockBcryptHasher) Compare(hashed string, literal string) error {
	ret := _mock.Called(hashed, literal)

	if len(ret) == 0 {
		panic("no return value specified for Compare")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(hashed, literal)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBcryptHasher_Compare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Compare'
type MockBcryptHasher_Compare_Call struct {
	*mock.Call
}

// Compare is a helper method to define mock.On call
//   - hashed string
//   - literal string
func (_e *MockBcryptHasher_Expecter) Compare(hashed any, literal any) *MockBcryptHasher_Compare_Call {
	return &MockBcryptHasher_Compare_Call{Call: _e.mock.On("Compare", hashed, literal)}
}

func (_c *MockBcryptHasher_Compare_Call) Run(run func(hashed string, literal string)) *MockBcryptHasher_Compare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBcryptHasher_Compare_Call) Return(err error) *MockBcryptHasher_Compare_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBcryptHasher_Compare_Call) RunAndReturn(run func(hashed string, literal string) error) *MockBcryptHasher_Compare_Call {
	_c.Call.Return(run)
	return _c
}

// Hash provides a mock function for the type MockBcryptHasher
func (_mock *MockBcryptHasher) Hash(literal string) ([]byte, error) {
	ret := _mock.Called(literal)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(literal)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(literal)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(literal)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBcryptHasher_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type MockBcryptHasher_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - literal string
func (_e *MockBcryptHasher_Expecter) Hash(literal any) *MockBcryptHasher_Hash_Call {
	return &MockBcryptHasher_Hash_Call{Call: _e.mock.On("Hash", literal)}
}

func (_c *MockBcryptHasher_Hash_Call) Run(run func(literal string)) *MockBcryptHasher_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBcryptHasher_Hash_Call) Return(bytes []byte, err error) *MockBcryptHasher_Hash_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockBcryptHasher_Hash_Call) RunAndReturn(run func(literal string) ([]byte, error)) *MockBcryptHasher_Hash_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJWTProvider creates a new instance of MockJWTProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJWTProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJWTProvider {
	mock := &MockJWTProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJWTProvider is an autogenerated mock type for the JWTProvider type
type MockJWTProvider struct {
	mock.Mock
}

type MockJWTProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJWTProvider) EXPECT() *MockJWTProvider_Expecter {
	return &MockJWTProvider_Expecter{mock: &_m.Mock}
}

// GenerateAccessToken provides a mock function for the type MockJWTProvider
func (_mock *MockJWTProvider) GenerateAccessToken(data *domain.User) (*domain.JWT, error) {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAccessToken")
	}

	var r0 *domain.JWT
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*domain.User) (*domain.JWT, error)); ok {
		return returnFunc(data)
	}
	if returnFunc, ok := ret.Get(0).(func(*domain.User) *domain.JWT); ok {
		r0 = returnFunc(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.JWT)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*domain.User) error); ok {
		r1 = returnFunc(data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJWTProvider_GenerateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateAccessToken'
type MockJWTProvider_GenerateAccessToken_Call struct {
	*mock.Call
}

// GenerateAccessToken is a helper method to define mock.On call
//   - data *domain.User
func (_e *MockJWTProvider_Expecter) GenerateAccessToken(data any) *MockJWTProvider_GenerateAccessToken_Call {
	return &MockJWTProvider_GenerateAccessToken_Call{Call: _e.mock.On("GenerateAccessToken", data)}
}

func (_c *MockJWTProvider_GenerateAccessToken_Call) Run(run func(data *domain.User)) *MockJWTProvider_GenerateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *domain.User
		if args[0] != nil {
			arg0 = args[0].(*domain.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJWTProvider_GenerateAccessToken_Call) Return(jWT *domain.JWT, err error) *MockJWTProvider_GenerateAccessToken_Call {
	_c.Call.Return(jWT, err)
	return _c
}

func (_c *MockJWTProvider_GenerateAccessToken_Call) RunAndReturn(run func(data *domain.User) (*domain.JWT, error)) *MockJWTProvider_GenerateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateRefreshToken provides a mock function for the type MockJWTProvider
func (_mock *MockJWTProvider) GenerateRefreshToken(data *domain.User) (*domain.JWT, error) {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for GenerateRefreshToken")
	}

	var r0 *domain.JWT
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*domain.User) (*domain.JWT, error)); ok {
		return returnFunc(data)
	}
	if returnFunc, ok := ret.Get(0).(func(*domain.User) *domain.JWT); ok {
		r0 = returnFunc(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.JWT)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*domain.User) error); ok {
		r1 = returnFunc(data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJWTProvider_GenerateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateRefreshToken'
type MockJWTProvider_GenerateRefreshToken_Call struct {
	*mock.Call
}

// GenerateRefreshToken is a helper method to define mock.On call
//   - data *domain.User
func (_e *MockJWTProvider_Expecter) GenerateRefreshToken(data any) *MockJWTProvider_GenerateRefreshToken_Call {
	return &MockJWTProvider_GenerateRefreshToken_Call{Call: _e.mock.On("GenerateRefreshToken", data)}
}

func (_c *MockJWTProvider_GenerateRefreshToken_Call) Run(run func(data *domain.User)) *MockJWTProvider_GenerateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *domain.User
		if args[0] != nil {
			arg0 = args[0].(*domain.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJWTProvider_GenerateRefreshToken_Call) Return(jWT *domain.JWT, err error) *MockJWTProvider_GenerateRefreshToken_Call {
	_c.Call.Return(jWT, err)
	return _c
}

func (_c *MockJWTProvider_GenerateRefreshToken_Call) RunAndReturn(run func(data *domain.User) (*domain.JWT, error)) *MockJWTProvider_GenerateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// ParseAccessToken provides a mock function for the type MockJWTProvider
func (_mock *MockJWTProvider) ParseAccessToken(tokenString string) (*domain.JWTPayload, error) {
	ret := _mock.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for ParseAccessToken")
	}

	var r0 *domain.JWTPayload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*domain.JWTPayload, error)); ok {
		return returnFunc(tokenString)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *domain.JWTPayload); ok {
		r0 = returnFunc(tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.JWTPayload)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(tokenString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJWTProvider_ParseAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseAccessToken'
type MockJWTProvider_ParseAccessToken_Call struct {
	*mock.Call
}

// ParseAccessToken is a helper method to define mock.On call
//   - tokenString string
func (_e *MockJWTProvider_Expecter) ParseAccessToken(tokenString any) *MockJWTProvider_ParseAccessToken_Call {
	return &MockJWTProvider_ParseAccessToken_Call{Call: _e.mock.On("ParseAccessToken", tokenString)}
}

func (_c *MockJWTProvider_ParseAccessToken_Call) Run(run func(tokenString string)) *MockJWTProvider_ParseAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJWTProvider_ParseAccessToken_Call) Return(jWTPayload *domain.JWTPayload, err error) *MockJWTProvider_ParseAccessToken_Call {
	_c.Call.Return(jWTPayload, err)
	return _c
}

func (_c *MockJWTProvider_ParseAccessToken_Call) RunAndReturn(run func(tokenString string) (*domain.JWTPayload, error)) *MockJWTProvider_ParseAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// ParseRefreshToken provides a mock function for the type MockJWTProvider
func (_mock *MockJWTProvider) ParseRefreshToken(tokenString string) (*domain.JWTPayload, error) {
	ret := _mock.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for ParseRefreshToken")
	}

	var r0 *domain.JWTPayload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*domain.JWTPayload, error)); ok {
		return returnFunc(tokenString)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *domain.JWTPayload); ok {
		r0 = returnFunc(tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.JWTPayload)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(tokenString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJWTProvider_ParseRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseRefreshToken'
type MockJWTProvider_ParseRefreshToken_Call struct {
	*mock.Call
}

// ParseRefreshToken is a helper method to define mock.On call
//   - tokenString string
func (_e *MockJWTProvider_Expecter) ParseRefreshToken(tokenString any) *MockJWTProvider_ParseRefreshToken_Call {
	return &MockJWTProvider_ParseRefreshToken_Call{Call: _e.mock.On("ParseRefreshToken", tokenString)}
}

func (_c *MockJWTProvider_ParseRefreshToken_Call) Run(run func(tokenString string)) *MockJWTProvider_ParseRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJWTProvider_ParseRefreshToken_Call) Return(jWTPayload *domain.JWTPayload, err error) *MockJWTProvider_ParseRefreshToken_Call {
	_c.Call.Return(jWTPayload, err)
	return _c
}

func (_c *MockJWTProvider_ParseRefreshToken_Call) RunAndReturn(run func(tokenString string) (*domain.JWTPayload, error)) *MockJWTProvider_ParseRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLogger creates a new instance of MockLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogger {
	mock := &MockLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLogger is an autogenerated mock type for the Logger type
type MockLogger struct {
	mock.Mock
}

type MockLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogger) EXPECT() *MockLogger_Expecter {
	return &MockLogger_Expecter{mock: &_m.Mock}
}

// Error provides a mock function for the type MockLogger
func (_mock *MockLogger) Error(msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(msg, args)
	} else {
		_mock.Called(msg)
	}

	return
}

// MockLogger_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockLogger_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - msg string
//   - args ...any
func (_e *MockLogger_Expecter) Error(msg any, args ...any) *MockLogger_Error_Call {
	return &MockLogger_Error_Call{Call: _e.mock.On("Error",
		append([]any{msg}, args...)...)}
}

func (_c *MockLogger_Error_Call) Run(run func(msg string, args ...any)) *MockLogger_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Error_Call) Return() *MockLogger_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Error_Call) RunAndReturn(run func(msg string, args ...any)) *MockLogger_Error_Call {
	_c.Run(run)
	return _c
}

// ErrorLog provides a mock function for the type MockLogger
func (_mock *MockLogger) ErrorLog(method string, path string, statusCode int, err error) {
	_mock.Called(method, path, statusCode, err)
	return
}

// MockLogger_ErrorLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ErrorLog'
type MockLogger_ErrorLog_Call struct {
	*mock.Call
}

// ErrorLog is a helper method to define mock.On call
//   - method string
//   - path string
//   - statusCode int
//   - err error
func (_e *MockLogger_Expecter) ErrorLog(method any, path any, statusCode any, err any) *MockLogger_ErrorLog_Call {
	return &MockLogger_ErrorLog_Call{Call: _e.mock.On("ErrorLog", method, path, statusCode, err)}
}

func (_c *MockLogger_ErrorLog_Call) Run(run func(method string, path string, statusCode int, err error)) *MockLogger_ErrorLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 error
		if args[3] != nil {
			arg3 = args[3].(error)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockLogger_ErrorLog_Call) Return() *MockLogger_ErrorLog_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_ErrorLog_Call) RunAndReturn(run func(method string, path string, statusCode int, err error)) *MockLogger_ErrorLog_Call {
	_c.Run(run)
	return _c
}

// Info provides a mock function for the type MockLogger
func (_mock *MockLogger) Info(msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(msg, args)
	} else {
		_mock.Called(msg)
	}

	return
}

// MockLogger_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockLogger_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - msg string
//   - args ...any
func (_e *MockLogger_Expecter) Info(msg any, args ...any) *MockLogger_Info_Call {
	return &MockLogger_Info_Call{Call: _e.mock.On("Info",
		append([]any{msg}, args...)...)}
}

func (_c *MockLogger_Info_Call) Run(run func(msg string, args ...any)) *MockLogger_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Info_Call) Return() *MockLogger_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Info_Call) RunAndReturn(run func(msg string, args ...any)) *MockLogger_Info_Call {
	_c.Run(run)
	return _c
}

// RequestLog provides a mock function for the type MockLogger
func (_mock *MockLogger) RequestLog(requestID string, method string, path string, statusCode int, start time.Time) {
	_mock.Called(requestID, method, path, statusCode, start)
	return
}

// MockLogger_RequestLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestLog'
type MockLogger_RequestLog_Call struct {
	*mock.Call
}

// RequestLog is a helper method to define mock.On call
//   - requestID string
//   - method string
//   - path string
//   - statusCode int
//   - start time.Time
func (_e *MockLogger_Expecter) RequestLog(requestID any, method any, path any, statusCode any, start any) *MockLogger_RequestLog_Call {
	return &MockLogger_RequestLog_Call{Call: _e.mock.On("RequestLog", requestID, method, path, statusCode, start)}
}

func (_c *MockLogger_RequestLog_Call) Run(run func(requestID string, method string, path string, statusCode int, start time.Time)) *MockLogger_RequestLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockLogger_RequestLog_Call) Return() *MockLogger_RequestLog_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_RequestLog_Call) RunAndReturn(run func(requestID string, method string, path string, statusCode int, start time.Time)) *MockLogger_RequestLog_Call {
	_c.Run(run)
	return _c
}

// Warn provides a mock function for the type MockLogger
func (_mock *MockLogger) Warn(msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(msg, args)
	} else {
		_mock.Called(msg)
	}

	return
}

// MockLogger_Warn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warn'
type MockLogger_Warn_Call struct {
	*mock.Call
}

// Warn is a helper method to define mock.On call
//   - msg string
//   - args ...any
func (_e *MockLogger_Expecter) Warn(msg any, args ...any) *MockLogger_Warn_Call {
	return &MockLogger_Warn_Call{Call: _e.mock.On("Warn",
		append([]any{msg}, args...)...)}
}

func (_c *MockLogger_Warn_Call) Run(run func(msg string, args ...any)) *MockLogger_Warn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Warn_Call) Return() *MockLogger_Warn_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Warn_Call) RunAndReturn(run func(msg string, args ...any)) *MockLogger_Warn_Call {
	_c.Run(run)
	return _c
}

// NewMockRedisClient creates a new instance of MockRedisClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRedisClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRedisClient {
	mock := &MockRedisClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRedisClient is an autogenerated mock type for the RedisClient type
type MockRedisClient struct {
	mock.Mock
}

type MockRedisClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRedisClient) EXPECT() *MockRedisClient_Expecter {
	return &MockRedisClient_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockRedisClient
func (_mock *MockRedisClient) Delete(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRedisClient_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRedisClient_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockRedisClient_Expecter) Delete(ctx any, key any) *MockRedisClient_Delete_Call {
	return &MockRedisClient_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockRedisClient_Delete_Call) Run(run func(ctx context.Context, key string)) *MockRedisClient_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRedisClient_Delete_Call) Return(err error) *MockRedisClient_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRedisClient_Delete_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockRedisClient_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockRedisClient
func (_mock *MockRedisClient) Get(ctx context.Context, key string) (string, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRedisClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRedisClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockRedisClient_Expecter) Get(ctx any, key any) *MockRedisClient_Get_Call {
	return &MockRedisClient_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockRedisClient_Get_Call) Run(run func(ctx context.Context, key string)) *MockRedisClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRedisClient_Get_Call) Return(s string, err error) *MockRedisClient_Get_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockRedisClient_Get_Call) RunAndReturn(run func(ctx context.Context, key string) (string, error)) *MockRedisClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockRedisClient
func (_mock *MockRedisClient) Set(ctx context.Context, key string, value any, expiration time.Duration) error {
	ret := _mock.Called(ctx, key, value, expiration)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, time.Duration) error); ok {
		r0 = returnFunc(ctx, key, value, expiration)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRedisClient_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockRedisClient_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value any
//   - expiration time.Duration
func (_e *MockRedisClient_Expecter) Set(ctx any, key any, value any, expiration any) *MockRedisClient_Set_Call {
	return &MockRedisClient_Set_Call{Call: _e.mock.On("Set", ctx, key, value, expiration)}
}

func (_c *MockRedisClient_Set_Call) Run(run func(ctx context.Context, key string, value any, expiration time.Duration)) *MockRedisClient_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRedisClient_Set_Call) Return(err error) *MockRedisClient_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRedisClient_Set_Call) RunAndReturn(run func(ctx context.Context, key string, value any, expiration time.Duration) error) *MockRedisClient_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockResendClient creates a new instance of MockResendClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResendClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResendClient {
	mock := &MockResendClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockResendClient is an autogenerated mock type for the ResendClient type
type MockResendClient struct {
	mock.Mock
}

type MockResendClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResendClient) EXPECT() *MockResendClient_Expecter {
	return &MockResendClient_Expecter{mock: &_m.Mock}
}

// SendRecoveryOTP provides a mock function for the type MockResendClient
func (_mock *MockResendClient) SendRecoveryOTP(ctx context.Context, account *domain.User, otp string) error {
	ret := _mock.Called(ctx, account, otp)

	if len(ret) == 0 {
		panic("no return value specified for SendRecoveryOTP")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.User, string) error); ok {
		r0 = returnFunc(ctx, account, otp)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockResendClient_SendRecoveryOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendRecoveryOTP'
type MockResendClient_SendRecoveryOTP_Call struct {
	*mock.Call
}

// SendRecoveryOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - account *domain.User
//   - otp string
func (_e *MockResendClient_Expecter) SendRecoveryOTP(ctx any, account any, otp any) *MockResendClient_SendRecoveryOTP_Call {
	return &MockResendClient_SendRecoveryOTP_Call{Call: _e.mock.On("SendRecoveryOTP", ctx, account, otp)}
}

func (_c *MockResendClient_SendRecoveryOTP_Call) Run(run func(ctx context.Context, account *domain.User, otp string)) *MockResendClient_SendRecoveryOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.User
		if args[1] != nil {
			arg1 = args[1].(*domain.User)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockResendClient_SendRecoveryOTP_Call) Return(err error) *MockResendClient_SendRecoveryOTP_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockResendClient_SendRecoveryOTP_Call) RunAndReturn(run func(ctx context.Context, account *domain.User, otp string) error) *MockResendClient_SendRecoveryOTP_Call {
	_c.Call.Return(run)
	return _c
}
