// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package user_mocks

import (
	"context"
	"main/internal/domain"
	"main/internal/modules/user"

	"github.com/gin-gonic/gin"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIController creates a new instance of MockIController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIController(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIController {
	mock := &MockIController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIController is an autogenerated mock type for the IController type
type MockIController struct {
	mock.Mock
}

type MockIController_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIController) EXPECT() *MockIController_Expecter {
	return &MockIController_Expecter{mock: &_m.Mock}
}

// AdminUpdateUser provides a mock function for the type MockIController
func (_mock *MockIController) AdminUpdateUser(c *gin.Context) {
	_mock.Called(c)
	return
}

// MockIController_AdminUpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdminUpdateUser'
type MockIController_AdminUpdateUser_Call struct {
	*mock.Call
}

// AdminUpdateUser is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockIController_Expecter) AdminUpdateUser(c any) *MockIController_AdminUpdateUser_Call {
	return &MockIController_AdminUpdateUser_Call{Call: _e.mock.On("AdminUpdateUser", c)}
}

func (_c *MockIController_AdminUpdateUser_Call) Run(run func(c *gin.Context)) *MockIController_AdminUpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIController_AdminUpdateUser_Call) Return() *MockIController_AdminUpdateUser_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIController_AdminUpdateUser_Call) RunAndReturn(run func(c *gin.Context)) *MockIController_AdminUpdateUser_Call {
	_c.Run(run)
	return _c
}

// CreateUser provides a mock function for the type MockIController
func (_mock *MockIController) CreateUser(c *gin.Context) {
	_mock.Called(c)
	return
}

// MockIController_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockIController_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockIController_Expecter) CreateUser(c any) *MockIController_CreateUser_Call {
	return &MockIController_CreateUser_Call{Call: _e.mock.On("CreateUser", c)}
}

func (_c *MockIController_CreateUser_Call) Run(run func(c *gin.Context)) *MockIController_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIController_CreateUser_Call) Return() *MockIController_CreateUser_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIController_CreateUser_Call) RunAndReturn(run func(c *gin.Context)) *MockIController_CreateUser_Call {
	_c.Run(run)
	return _c
}

// DeleteUser provides a mock function for the type MockIController
func (_mock *MockIController) DeleteUser(c *gin.Context) {
	_mock.Called(c)
	return
}

// MockIController_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockIController_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockIController_Expecter) DeleteUser(c any) *MockIController_DeleteUser_Call {
	return &MockIController_DeleteUser_Call{Call: _e.mock.On("DeleteUser", c)}
}

func (_c *MockIController_DeleteUser_Call) Run(run func(c *gin.Context)) *MockIController_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIController_DeleteUser_Call) Return() *MockIController_DeleteUser_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIController_DeleteUser_Call) RunAndReturn(run func(c *gin.Context)) *MockIController_DeleteUser_Call {
	_c.Run(run)
	return _c
}

// GetMyAccount provides a mock function for the type MockIController
func (_mock *MockIController) GetMyAccount(c *gin.Context) {
	_mock.Called(c)
	return
}

// MockIController_GetMyAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMyAccount'
type MockIController_GetMyAccount_Call struct {
	*mock.Call
}

// GetMyAccount is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockIController_Expecter) GetMyAccount(c any) *MockIController_GetMyAccount_Call {
	return &MockIController_GetMyAccount_Call{Call: _e.mock.On("GetMyAccount", c)}
}

func (_c *MockIController_GetMyAccount_Call) Run(run func(c *gin.Context)) *MockIController_GetMyAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIController_GetMyAccount_Call) Return() *MockIController_GetMyAccount_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIController_GetMyAccount_Call) RunAndReturn(run func(c *gin.Context)) *MockIController_GetMyAccount_Call {
	_c.Run(run)
	return _c
}

// GetUserByID provides a mock function for the type MockIController
func (_mock *MockIController) GetUserByID(c *gin.Context) {
	_mock.Called(c)
	return
}

// MockIController_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockIController_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockIController_Expecter) GetUserByID(c any) *MockIController_GetUserByID_Call {
	return &MockIController_GetUserByID_Call{Call: _e.mock.On("GetUserByID", c)}
}

func (_c *MockIController_GetUserByID_Call) Run(run func(c *gin.Context)) *MockIController_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIController_GetUserByID_Call) Return() *MockIController_GetUserByID_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIController_GetUserByID_Call) RunAndReturn(run func(c *gin.Context)) *MockIController_GetUserByID_Call {
	_c.Run(run)
	return _c
}

// GetUserBySystemID provides a mock function for the type MockIController
func (_mock *MockIController) GetUserBySystemID(c *gin.Context) {
	_mock.Called(c)
	return
}

// MockIController_GetUserBySystemID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserBySystemID'
type MockIController_GetUserBySystemID_Call struct {
	*mock.Call
}

// GetUserBySystemID is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockIController_Expecter) GetUserBySystemID(c any) *MockIController_GetUserBySystemID_Call {
	return &MockIController_GetUserBySystemID_Call{Call: _e.mock.On("GetUserBySystemID", c)}
}

func (_c *MockIController_GetUserBySystemID_Call) Run(run func(c *gin.Context)) *MockIController_GetUserBySystemID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIController_GetUserBySystemID_Call) Return() *MockIController_GetUserBySystemID_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIController_GetUserBySystemID_Call) RunAndReturn(run func(c *gin.Context)) *MockIController_GetUserBySystemID_Call {
	_c.Run(run)
	return _c
}

// UpdateUser provides a mock function for the type MockIController
func (_mock *MockIController) UpdateUser(c *gin.Context) {
	_mock.Called(c)
	return
}

// MockIController_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockIController_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockIController_Expecter) UpdateUser(c any) *MockIController_UpdateUser_Call {
	return &MockIController_UpdateUser_Call{Call: _e.mock.On("UpdateUser", c)}
}

func (_c *MockIController_UpdateUser_Call) Run(run func(c *gin.Context)) *MockIController_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIController_UpdateUser_Call) Return() *MockIController_UpdateUser_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIController_UpdateUser_Call) RunAndReturn(run func(c *gin.Context)) *MockIController_UpdateUser_Call {
	_c.Run(run)
	return _c
}

// NewMockIRepository creates a new instance of MockIRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRepository {
	mock := &MockIRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIRepository is an autogenerated mock type for the IRepository type
type MockIRepository struct {
	mock.Mock
}

type MockIRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRepository) EXPECT() *MockIRepository_Expecter {
	return &MockIRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockIRepository
func (_mock *MockIRepository) Create(ctx context.Context, data *domain.User) (*domain.User, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.User) (*domain.User, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.User) *domain.User); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.User) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - data *domain.User
func (_e *MockIRepository_Expecter) Create(ctx any, data any) *MockIRepository_Create_Call {
	return &MockIRepository_Create_Call{Call: _e.mock.On("Create", ctx, data)}
}

func (_c *MockIRepository_Create_Call) Run(run func(ctx context.Context, data *domain.User)) *MockIRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.User
		if args[1] != nil {
			arg1 = args[1].(*domain.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIRepository_Create_Call) Return(user *domain.User, err error) *MockIRepository_Create_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockIRepository_Create_Call) RunAndReturn(run func(ctx context.Context, data *domain.User) (*domain.User, error)) *MockIRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockIRepository
func (_mock *MockIRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockIRepository_Expecter) Delete(ctx any, id any) *MockIRepository_Delete_Call {
	return &MockIRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockIRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockIRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIRepository_Delete_Call) Return(err error) *MockIRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockIRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function for the type MockIRepository
func (_mock *MockIRepository) FindByEmail(ctx context.Context, email string) (*domain.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRepository_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockIRepository_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockIRepository_Expecter) FindByEmail(ctx any, email any) *MockIRepository_FindByEmail_Call {
	return &MockIRepository_FindByEmail_Call{Call: _e.mock.On("FindByEmail", ctx, email)}
}

func (_c *MockIRepository_FindByEmail_Call) Run(run func(ctx context.Context, email string)) *MockIRepository_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIRepository_FindByEmail_Call) Return(user *domain.User, err error) *MockIRepository_FindByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockIRepository_FindByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*domain.User, error)) *MockIRepository_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockIRepository
func (_mock *MockIRepository) FindByID(ctx context.Context, id uuid.UUID) (*domain.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockIRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockIRepository_Expecter) FindByID(ctx any, id any) *MockIRepository_FindByID_Call {
	return &MockIRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockIRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockIRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIRepository_FindByID_Call) Return(user *domain.User, err error) *MockIRepository_FindByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockIRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*domain.User, error)) *MockIRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindBySystemID provides a mock function for the type MockIRepository
func (_mock *MockIRepository) FindBySystemID(ctx context.Context, id string) (*domain.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindBySystemID")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRepository_FindBySystemID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySystemID'
type MockIRepository_FindBySystemID_Call struct {
	*mock.Call
}

// FindBySystemID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockIRepository_Expecter) FindBySystemID(ctx any, id any) *MockIRepository_FindBySystemID_Call {
	return &MockIRepository_FindBySystemID_Call{Call: _e.mock.On("FindBySystemID", ctx, id)}
}

func (_c *MockIRepository_FindBySystemID_Call) Run(run func(ctx context.Context, id string)) *MockIRepository_FindBySystemID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIRepository_FindBySystemID_Call) Return(user *domain.User, err error) *MockIRepository_FindBySystemID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockIRepository_FindBySystemID_Call) RunAndReturn(run func(ctx context.Context, id string) (*domain.User, error)) *MockIRepository_FindBySystemID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockIRepository
func (_mock *MockIRepository) Update(ctx context.Context, data *domain.User) (*domain.User, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.User) (*domain.User, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.User) *domain.User); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.User) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - data *domain.User
func (_e *MockIRepository_Expecter) Update(ctx any, data any) *MockIRepository_Update_Call {
	return &MockIRepository_Update_Call{Call: _e.mock.On("Update", ctx, data)}
}

func (_c *MockIRepository_Update_Call) Run(run func(ctx context.Context, data *domain.User)) *MockIRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.User
		if args[1] != nil {
			arg1 = args[1].(*domain.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIRepository_Update_Call) Return(user *domain.User, err error) *MockIRepository_Update_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockIRepository_Update_Call) RunAndReturn(run func(ctx context.Context, data *domain.User) (*domain.User, error)) *MockIRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIUseCase creates a new instance of MockIUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIUseCase {
	mock := &MockIUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIUseCase is an autogenerated mock type for the IUseCase type
type MockIUseCase struct {
	mock.Mock
}

type MockIUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIUseCase) EXPECT() *MockIUseCase_Expecter {
	return &MockIUseCase_Expecter{mock: &_m.Mock}
}

// AdminUpdateUser provides a mock function for the type MockIUseCase
func (_mock *MockIUseCase) AdminUpdateUser(ctx context.Context, data *user.AdminUpdateUserDTO) (*user.UserResponse, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for AdminUpdateUser")
	}

	var r0 *user.UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *user.AdminUpdateUserDTO) (*user.UserResponse, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *user.AdminUpdateUserDTO) *user.UserResponse); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.UserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *user.AdminUpdateUserDTO) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUseCase_AdminUpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdminUpdateUser'
type MockIUseCase_AdminUpdateUser_Call struct {
	*mock.Call
}

// AdminUpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - data *user.AdminUpdateUserDTO
func (_e *MockIUseCase_Expecter) AdminUpdateUser(ctx any, data any) *MockIUseCase_AdminUpdateUser_Call {
	return &MockIUseCase_AdminUpdateUser_Call{Call: _e.mock.On("AdminUpdateUser", ctx, data)}
}

func (_c *MockIUseCase_AdminUpdateUser_Call) Run(run func(ctx context.Context, data *user.AdminUpdateUserDTO)) *MockIUseCase_AdminUpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *user.AdminUpdateUserDTO
		if args[1] != nil {
			arg1 = args[1].(*user.AdminUpdateUserDTO)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUseCase_AdminUpdateUser_Call) Return(userResponse *user.UserResponse, err error) *MockIUseCase_AdminUpdateUser_Call {
	_c.Call.Return(userResponse, err)
	return _c
}

func (_c *MockIUseCase_AdminUpdateUser_Call) RunAndReturn(run func(ctx context.Context, data *user.AdminUpdateUserDTO) (*user.UserResponse, error)) *MockIUseCase_AdminUpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type MockIUseCase
func (_mock *MockIUseCase) CreateUser(ctx context.Context, data *user.CreateUserSchema) (*user.UserResponse, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *user.UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *user.CreateUserSchema) (*user.UserResponse, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *user.CreateUserSchema) *user.UserResponse); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.UserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *user.CreateUserSchema) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUseCase_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockIUseCase_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - data *user.CreateUserSchema
func (_e *MockIUseCase_Expecter) CreateUser(ctx any, data any) *MockIUseCase_CreateUser_Call {
	return &MockIUseCase_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, data)}
}

func (_c *MockIUseCase_CreateUser_Call) Run(run func(ctx context.Context, data *user.CreateUserSchema)) *MockIUseCase_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *user.CreateUserSchema
		if args[1] != nil {
			arg1 = args[1].(*user.CreateUserSchema)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUseCase_CreateUser_Call) Return(userResponse *user.UserResponse, err error) *MockIUseCase_CreateUser_Call {
	_c.Call.Return(userResponse, err)
	return _c
}

func (_c *MockIUseCase_CreateUser_Call) RunAndReturn(run func(ctx context.Context, data *user.CreateUserSchema) (*user.UserResponse, error)) *MockIUseCase_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type MockIUseCase
func (_mock *MockIUseCase) DeleteUser(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIUseCase_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockIUseCase_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockIUseCase_Expecter) DeleteUser(ctx any, id any) *MockIUseCase_DeleteUser_Call {
	return &MockIUseCase_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, id)}
}

func (_c *MockIUseCase_DeleteUser_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockIUseCase_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUseCase_DeleteUser_Call) Return(err error) *MockIUseCase_DeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIUseCase_DeleteUser_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockIUseCase_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockIUseCase
func (_mock *MockIUseCase) GetUserByID(ctx context.Context, id uuid.UUID) (*user.UserResponse, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *user.UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*user.UserResponse, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *user.UserResponse); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.UserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUseCase_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockIUseCase_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockIUseCase_Expecter) GetUserByID(ctx any, id any) *MockIUseCase_GetUserByID_Call {
	return &MockIUseCase_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *MockIUseCase_GetUserByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockIUseCase_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUseCase_GetUserByID_Call) Return(userResponse *user.UserResponse, err error) *MockIUseCase_GetUserByID_Call {
	_c.Call.Return(userResponse, err)
	return _c
}

func (_c *MockIUseCase_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*user.UserResponse, error)) *MockIUseCase_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserBySystemID provides a mock function for the type MockIUseCase
func (_mock *MockIUseCase) GetUserBySystemID(ctx context.Context, id string) (*user.UserResponse, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserBySystemID")
	}

	var r0 *user.UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*user.UserResponse, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *user.UserResponse); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.UserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUseCase_GetUserBySystemID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserBySystemID'
type MockIUseCase_GetUserBySystemID_Call struct {
	*mock.Call
}

// GetUserBySystemID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockIUseCase_Expecter) GetUserBySystemID(ctx any, id any) *MockIUseCase_GetUserBySystemID_Call {
	return &MockIUseCase_GetUserBySystemID_Call{Call: _e.mock.On("GetUserBySystemID", ctx, id)}
}

func (_c *MockIUseCase_GetUserBySystemID_Call) Run(run func(ctx context.Context, id string)) *MockIUseCase_GetUserBySystemID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUseCase_GetUserBySystemID_Call) Return(userResponse *user.UserResponse, err error) *MockIUseCase_GetUserBySystemID_Call {
	_c.Call.Return(userResponse, err)
	return _c
}

func (_c *MockIUseCase_GetUserBySystemID_Call) RunAndReturn(run func(ctx context.Context, id string) (*user.UserResponse, error)) *MockIUseCase_GetUserBySystemID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function for the type MockIUseCase
func (_mock *MockIUseCase) UpdateUser(ctx context.Context, data *user.UpdateUserDTO) (*user.UserResponse, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 *user.UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *user.UpdateUserDTO) (*user.UserResponse, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *user.UpdateUserDTO) *user.UserResponse); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.UserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *user.UpdateUserDTO) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUseCase_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockIUseCase_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - data *user.UpdateUserDTO
func (_e *MockIUseCase_Expecter) UpdateUser(ctx any, data any) *MockIUseCase_UpdateUser_Call {
	return &MockIUseCase_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, data)}
}

func (_c *MockIUseCase_UpdateUser_Call) Run(run func(ctx context.Context, data *user.UpdateUserDTO)) *MockIUseCase_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *user.UpdateUserDTO
		if args[1] != nil {
			arg1 = args[1].(*user.UpdateUserDTO)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUseCase_UpdateUser_Call) Return(userResponse *user.UserResponse, err error) *MockIUseCase_UpdateUser_Call {
	_c.Call.Return(userResponse, err)
	return _c
}

func (_c *MockIUseCase_UpdateUser_Call) RunAndReturn(run func(ctx context.Context, data *user.UpdateUserDTO) (*user.UserResponse, error)) *MockIUseCase_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}
