// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"main/internal/modules/class/domain"
	"main/internal/modules/class/dto"
	"main/internal/shared/pagination"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClassUseCaseI creates a new instance of MockClassUseCaseI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClassUseCaseI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClassUseCaseI {
	mock := &MockClassUseCaseI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClassUseCaseI is an autogenerated mock type for the ClassUseCaseI type
type MockClassUseCaseI struct {
	mock.Mock
}

type MockClassUseCaseI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClassUseCaseI) EXPECT() *MockClassUseCaseI_Expecter {
	return &MockClassUseCaseI_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockClassUseCaseI
func (_mock *MockClassUseCaseI) Create(ctx context.Context, data *dto.CreateClassRequest) (*domain.Class, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Class
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.CreateClassRequest) (*domain.Class, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.CreateClassRequest) *domain.Class); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Class)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.CreateClassRequest) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClassUseCaseI_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockClassUseCaseI_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - data *dto.CreateClassRequest
func (_e *MockClassUseCaseI_Expecter) Create(ctx any, data any) *MockClassUseCaseI_Create_Call {
	return &MockClassUseCaseI_Create_Call{Call: _e.mock.On("Create", ctx, data)}
}

func (_c *MockClassUseCaseI_Create_Call) Run(run func(ctx context.Context, data *dto.CreateClassRequest)) *MockClassUseCaseI_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.CreateClassRequest
		if args[1] != nil {
			arg1 = args[1].(*dto.CreateClassRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClassUseCaseI_Create_Call) Return(class *domain.Class, err error) *MockClassUseCaseI_Create_Call {
	_c.Call.Return(class, err)
	return _c
}

func (_c *MockClassUseCaseI_Create_Call) RunAndReturn(run func(ctx context.Context, data *dto.CreateClassRequest) (*domain.Class, error)) *MockClassUseCaseI_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockClassUseCaseI
func (_mock *MockClassUseCaseI) Delete(ctx context.Context, classID uuid.UUID) error {
	ret := _mock.Called(ctx, classID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, classID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClassUseCaseI_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockClassUseCaseI_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - classID uuid.UUID
func (_e *MockClassUseCaseI_Expecter) Delete(ctx any, classID any) *MockClassUseCaseI_Delete_Call {
	return &MockClassUseCaseI_Delete_Call{Call: _e.mock.On("Delete", ctx, classID)}
}

func (_c *MockClassUseCaseI_Delete_Call) Run(run func(ctx context.Context, classID uuid.UUID)) *MockClassUseCaseI_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClassUseCaseI_Delete_Call) Return(err error) *MockClassUseCaseI_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClassUseCaseI_Delete_Call) RunAndReturn(run func(ctx context.Context, classID uuid.UUID) error) *MockClassUseCaseI_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockClassUseCaseI
func (_mock *MockClassUseCaseI) GetAll(ctx context.Context, pagination1 *pagination.Pagination) (*[]domain.Class, int, error) {
	ret := _mock.Called(ctx, pagination1)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 *[]domain.Class
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pagination.Pagination) (*[]domain.Class, int, error)); ok {
		return returnFunc(ctx, pagination1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pagination.Pagination) *[]domain.Class); ok {
		r0 = returnFunc(ctx, pagination1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]domain.Class)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *pagination.Pagination) int); ok {
		r1 = returnFunc(ctx, pagination1)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *pagination.Pagination) error); ok {
		r2 = returnFunc(ctx, pagination1)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockClassUseCaseI_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockClassUseCaseI_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - pagination1 *pagination.Pagination
func (_e *MockClassUseCaseI_Expecter) GetAll(ctx any, pagination1 any) *MockClassUseCaseI_GetAll_Call {
	return &MockClassUseCaseI_GetAll_Call{Call: _e.mock.On("GetAll", ctx, pagination1)}
}

func (_c *MockClassUseCaseI_GetAll_Call) Run(run func(ctx context.Context, pagination1 *pagination.Pagination)) *MockClassUseCaseI_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *pagination.Pagination
		if args[1] != nil {
			arg1 = args[1].(*pagination.Pagination)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClassUseCaseI_GetAll_Call) Return(classs *[]domain.Class, n int, err error) *MockClassUseCaseI_GetAll_Call {
	_c.Call.Return(classs, n, err)
	return _c
}

func (_c *MockClassUseCaseI_GetAll_Call) RunAndReturn(run func(ctx context.Context, pagination1 *pagination.Pagination) (*[]domain.Class, int, error)) *MockClassUseCaseI_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockClassUseCaseI
func (_mock *MockClassUseCaseI) GetByID(ctx context.Context, classID uuid.UUID) (*domain.Class, error) {
	ret := _mock.Called(ctx, classID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Class
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Class, error)); ok {
		return returnFunc(ctx, classID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Class); ok {
		r0 = returnFunc(ctx, classID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Class)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, classID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClassUseCaseI_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockClassUseCaseI_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - classID uuid.UUID
func (_e *MockClassUseCaseI_Expecter) GetByID(ctx any, classID any) *MockClassUseCaseI_GetByID_Call {
	return &MockClassUseCaseI_GetByID_Call{Call: _e.mock.On("GetByID", ctx, classID)}
}

func (_c *MockClassUseCaseI_GetByID_Call) Run(run func(ctx context.Context, classID uuid.UUID)) *MockClassUseCaseI_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClassUseCaseI_GetByID_Call) Return(class *domain.Class, err error) *MockClassUseCaseI_GetByID_Call {
	_c.Call.Return(class, err)
	return _c
}

func (_c *MockClassUseCaseI_GetByID_Call) RunAndReturn(run func(ctx context.Context, classID uuid.UUID) (*domain.Class, error)) *MockClassUseCaseI_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBySystemID provides a mock function for the type MockClassUseCaseI
func (_mock *MockClassUseCaseI) GetBySystemID(ctx context.Context, systemID string) (*domain.Class, error) {
	ret := _mock.Called(ctx, systemID)

	if len(ret) == 0 {
		panic("no return value specified for GetBySystemID")
	}

	var r0 *domain.Class
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Class, error)); ok {
		return returnFunc(ctx, systemID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Class); ok {
		r0 = returnFunc(ctx, systemID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Class)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, systemID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClassUseCaseI_GetBySystemID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBySystemID'
type MockClassUseCaseI_GetBySystemID_Call struct {
	*mock.Call
}

// GetBySystemID is a helper method to define mock.On call
//   - ctx context.Context
//   - systemID string
func (_e *MockClassUseCaseI_Expecter) GetBySystemID(ctx any, systemID any) *MockClassUseCaseI_GetBySystemID_Call {
	return &MockClassUseCaseI_GetBySystemID_Call{Call: _e.mock.On("GetBySystemID", ctx, systemID)}
}

func (_c *MockClassUseCaseI_GetBySystemID_Call) Run(run func(ctx context.Context, systemID string)) *MockClassUseCaseI_GetBySystemID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClassUseCaseI_GetBySystemID_Call) Return(class *domain.Class, err error) *MockClassUseCaseI_GetBySystemID_Call {
	_c.Call.Return(class, err)
	return _c
}

func (_c *MockClassUseCaseI_GetBySystemID_Call) RunAndReturn(run func(ctx context.Context, systemID string) (*domain.Class, error)) *MockClassUseCaseI_GetBySystemID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockClassUseCaseI
func (_mock *MockClassUseCaseI) Update(ctx context.Context, data *dto.UpdateClassRequest) (*domain.Class, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Class
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.UpdateClassRequest) (*domain.Class, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.UpdateClassRequest) *domain.Class); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Class)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.UpdateClassRequest) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClassUseCaseI_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockClassUseCaseI_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - data *dto.UpdateClassRequest
func (_e *MockClassUseCaseI_Expecter) Update(ctx any, data any) *MockClassUseCaseI_Update_Call {
	return &MockClassUseCaseI_Update_Call{Call: _e.mock.On("Update", ctx, data)}
}

func (_c *MockClassUseCaseI_Update_Call) Run(run func(ctx context.Context, data *dto.UpdateClassRequest)) *MockClassUseCaseI_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.UpdateClassRequest
		if args[1] != nil {
			arg1 = args[1].(*dto.UpdateClassRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClassUseCaseI_Update_Call) Return(class *domain.Class, err error) *MockClassUseCaseI_Update_Call {
	_c.Call.Return(class, err)
	return _c
}

func (_c *MockClassUseCaseI_Update_Call) RunAndReturn(run func(ctx context.Context, data *dto.UpdateClassRequest) (*domain.Class, error)) *MockClassUseCaseI_Update_Call {
	_c.Call.Return(run)
	return _c
}
